#+TAGS: db oracle 11g 12c


* Oracle Database
Forum: http://forums.oracle.com
11g docs: https://docs.oracle.com/cd/E11882_01/index.htm

* cmds
- sqlplus - client
* Description
* Usage
** Oracle 11g
url: https://docs.oracle.com/en/database/
** Installing on Centos7 (VM)
Oracle-Base: https://oracle-base.com/articles/11g/oracle-db-11gr2-installation-on-oracle-linux-7

- Overview
  - Download Software
  - Unpack Files
  - Edit host file
  - Oracle Installation Prerequisites
    - Automatic Setup
    - Manual Setup
    - Additional Setup
  - Installation
  - Post Installation

*** Download the Oracle DB 11g from website
http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html

*** Unpack Files
- the unzip utilitiy is required
#+BEGIN_SRC sh
yum install unzip
#+END_SRC

- unzip files
#+BEGIN_SRC sh
unzip linux.x64_11gR2_database_1of2.zip
unzip linux.x64_11gR2_database_2of2.zip
#+END_SRC
  
*** Hosts File
/etc/hosts
#+BEGIN_EXAMPLE
127.0.0.1       localhost 
192.168.0.215   oracledb
#+END_EXAMPLE

/etc/hostname
#+BEGIN_EXAMPLE
oracledb
#+END_EXAMPLE
  
*** Oracle Installation Prerequisites
Option of either the Automatic setup or the Manual setup.
The Additional setup is required for all installations.

**** Automatic
for the automatic install the Oracle Linux repo has to be installed
#+BEGIN_SRC sh
cd /etc/yum.repos.d
wget http://yum.oracle.com/public-yum-ol7.repo
#+END_SRC
the ol7 represents the versiion of Oracle Linux

- I had to import the oracle gpg key
https://docs.oracle.com/cd/E52668_01/E39381/html/ol_import_gpg.html
#+BEGIN_SRC sh
wget http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol7
gpg --quiet --with-fingerprint ./RPM-GPG-KEY-oracle-ol7
rpm --import ./RPM-GPG-KEY-oracle-ol7
#+END_SRC

- now for the automatic setup
#+BEGIN_SRC sh
yum install oracle-rdbms-server-11gR2-preinstall
yum update
#+END_SRC

**** Manual
   
**** Additional
- set the oracle user password
#+BEGIN_SRC sh
passwd oracle
#+END_SRC

- Configure SELinux to be permissive
/etc/selinux/config
#+BEGIN_EXAMPLE
SELINUX=permissive
#+END_EXAMPLE

- and set the current state to permissive
#+BEGIN_SRC sh
setenforce 0
#+END_SRC

- disable the firewall
#+BEGIN_SRC sh
systemctl stop firewalld
systemctl disable firewalld
#+END_SRC

- Create the dirs where the software will be installed
#+BEGIN_SRC sh
mkdir -p /u01/app/oracle/product/11.2.0.4/db_1
chown -R oracle:oinstall /u01
chmod -R 775 /u01
#+END_SRC

- add the Oracle settigns to the oracle users bash_profile
#+BEGIN_EXAMPLE
# Oracle Settings
TMP=/tmp; export TMP
TMPDIR=$TMP; export TMPDIR

ORACLE_HOSTNAME=ol7.localdomain; export ORACLE_HOSTNAME
ORACLE_UNQNAME=DB11G; export ORACLE_UNQNAME
ORACLE_BASE=/u01/app/oracle; export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/11.2.0.4/db_1; export ORACLE_HOME
ORACLE_SID=DB11G; export ORACLE_SID
ORACLE_TERM=xterm; export ORACLE_TERM
PATH=/usr/sbin:$PATH; export PATH
PATH=$ORACLE_HOME/bin:$PATH; export PATH

LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
CLASSPATH=$ORACLE_HOME/JRE:$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib; export CLASSPATH
#+END_EXAMPLE

- switch to oracle user to install the software
#+BEGIN_SRC sh
./runInstaller
#+END_SRC
this will start the GUI installer

* Lecture
** [[https://www.youtube.com/watch?v=addFo5FMzkg][Oracle SGA Architecture Overview - Pete Cassidy]]
* Tutorial
** CBT Nuggets Oracle Database 11g SQL Fundamentals 1z0-051
*** Lesson 2 - About SQL
- Dr E F Codd, IBM 1970 - legendary paper 

- SQL --> Chamberlain + Boyce @ IBM --> SEQEUEL
  
- DDL - Data Definition Language
  - create
  - alter
  - drop
    
- DML - Data Manipulation Language
  - select - read from the DB
  - insert
  - update - modifiy a value
  - delete - delete a value
    
- DCL - Data Control Language
  - grant
  - revoke

- TxCL - Transaction Control Language
  - commit
  - rollback
  - savepoint

- SQL Variants
  - ANSI 
  - PL/SQL - Oracle
  - Transact-SQL - M$
  - MySQL - Oracle
    - MariaDB
  - IBM DB2
  - PostgeSQL

- SQL * Plus
  - interactive/batch cli for OracleDB
    - server
    - client
      
- cmd types
  - SQL * Plus
  - SQL
  - PL/SQL
  - Host OS

*** Lesson 3 - The Select Statement
- Schemas
  - Defn - logical container for data structures
  - same name for tables can be used if created by different users
    - emp, hr.emp, lisa.emp are all able to coexist ownership is part of the nameing
      
- Functions of SELECT
  - projection: columns
  - selection: rows
  - jions: > 1 related tables
    
  - SQL statements are case-insensitive
    #+BEGIN_EXAMPLE
    SELECT _______ FROM ______;
    #+END_EXAMPLE
  - SELECT
    - * - all
    - col,col <----- EID, first_name, last_name - order of the colums are how oracle will give the data back
    - Distinct - only show unique enteries
    - expression
      - + * - /
      - uses the nomal mathmatical order of precidents 
	
  - Describing Table Structure
    - DESCRIBE / DESC
      - Reveals data types

SQLPLUS
- Formating Colums
#+BEGIN_EXAMPLE
SQL> column salary format $99,999.99;
#+END_EXAMPLE
this will display salary as an actual monatary values apose to just a number

- Clear Screen
#+BEGIN_EXAMPLE
SQL> host clear
#+END_EXAMPLE

- View Current Buffer
#+BEGIN_EXAMPLE
SQL> l
#+END_EXAMPLE

- Write output to a file
#+BEGIN_EXAMPLE
SQL> spool employees.txt
SQL> SELECT * FROM emploees;
SQL> spool off
#+END_EXAMPLE

- move out to the shell
#+BEGIN_EXAMPLE
SQL> host
$ exit
SQL>
#+END_EXAMPLE

*** Lesson 4 - Continuation of the Select Statement

Restricting/Sorting Data
  - limiting Rows
    - WHERE
  - Sorting Rows
    - ORDER BY
      
SELECT
FROM
WHERE

Filtering Strings and Dates
  - need single quotation marks
    #+BEGIN_EXAMPLE
    last_name = 'Warner'
    crt_date  = '20-AUG-84'
    #+END_EXAMPLE
  - case-sensitive and date format sensitive (DD-MMM-YY is the default date format)
    
Wildcard Searches
  - % = >= 0 characters - analogous to *
  - _ = 1 character     - analogous to .
    
Regexp Exp
#+BEGIN_EXAMPLE
hire_date LIKE '%98'   # all employees from 98
last_name LIKE 'S%'    # all employees with a last name that begins with 'S'
last_name LIKE '_ith%' # all employees with a last name that contains *ith*
#+END_EXAMPLE

Precedence Rules for WHERE
1. Arithmetic
2. Concat
3. Comparisons
4. IS(NOT)NULL, LIKE, (NOT)IN
5. (NOT)BETWEEN
6. Noteuqal
7. Not
8. AND
9. OR
   
Ordering Query Results

SELECT
FROM
*WHERE* - optional
ORDER BY ----> ASC  - a-z 1-99 (default)
         ----> DESC - z-a 99-1 

- without ORDER BY, oracle uses an 'undefined' sort order
  

Examples of WHERE  
#+BEGIN_EXAMPLE
SELECT table_name FROM user_tables;

SELECT employee_id, first_name, last_name, department_id FROM employees 
WHERE department_id = 100;

SELECT * FROM departments 
WHERE location_id = 50;

SELECT emmployee_id, first_name, last_name FROM employees 
WHERE last_name = 'King';

SELECT employee_id first_name, last_name FROM employees 
WHERE last_name = 'King' 
AND first_name = 'Janette';

SELECT employee_id, first_name, last_name, salary FROM employees 
WHERE salary > 14000;

SELECT employee_id, first_name, last_name, salary FROM employees 
WHERE salary <= 14000;

SELECT employee_id, first_name, last_name, hire_date FROM employees
WHERE hire_date > '01-JAN-07'
ORDER BY hire_date ASC;

SELECT employee_id, first_name, last_name, hire_date FROM employees
WHERE hire_date BETWEEN '01-JAN-07' AND '01-JAN-08'

SELECT employee_id, first_name, last_name, hire_date FROM employees
WHERE last_name BETWEEN 'Chung' AND 'Ozer';

SELECT employee_id, first_name, last_name, hire_date FROM employees
WHERE last_name BETWEEN 'C%' AND 'E%';

-- This will return only employees with last names of 'Chung' or 'Ozer' 
SELECT employee_id, first_name, last_name, hire_date FROM employees
WHERE last_name IN ('Chung', 'Ozer'); 

-- Everyone but 'Chung' and 'Ozer'
SELECT employee_id, first_name, last_name, hire_date FROM employees
WHERE last_name NOT IN ('Chung', 'Ozer'); 

SELECT employee_id, first_name, last_name, manager_id FROM employees
WHERE manager_id IN (101, 103, 123);

SELECT first_name, last_name FROM employees
WHERE last_name LIKE 'S%';

SELECT first_name, last_name FROM employees
WHERE last_name NOT LIKE 'S%';

SELECT employee_id, first_name, last_name, commission_pct FROM employees
WHERE commission_pact is NULL;

SELECT employee_id, first_name, last_name, salary FROM employees 
WHERE salary > 10000
AND last_name LIKE '%i%';

SELECT employee_id, first_name, last_name, salary FROM employees 
WHERE salary > 10000
OR last_name LIKE 'S%'
ORDER BY salary ASC;
#+END_EXAMPLE

Substitution Variables 
  - & - only available in sqlplus or sqldev

  &user_var  -> prompt @ query runtime
  &&user_var -> prompt once, reuse many times
  
*** Lesson 5 - Single-Row Functions

Types of SR Functions
  - character - Lower, Upper, Concat
  - number - Round, Trunc
  - date - SYSDATE, MONTHS__BETWEEN
  - Conversion - datatype conversion
      - implicit (by Oracle)
      - explicit (by DBA)
	
- when a function is called the product is returned in a pseudo column
  
- Implicit
  - DATE to VARCHAR2
  - NUMBER to VARCHAR2
  - VARCHAR/CHAR to NUMBER
  - VARCHAR/CHAR to DATE
    
- Explicit (type casting)
  - TO_CHAR(num,date)
  - TO_NUMBER(char)
  - TO_DATE(char)
    
The Dual Table
  - Is a builtin table
  - Shouldn't be modified
  - SELECT requires FROM - so for calls to the system the dual is used
    
Examples of using SR Functions
#+BEGIN_EXAMPLE
-- This shows the sr for changing case of column
SELECT job_id, LOWER(job_id), INITCAP(job_id), job_title, UPPER(job_title)
FROM jobs; 

SELECT 2 + 2 AS Sum FROM dual;

SELECT LENGTH('Hello world!!') AS length  FROM dual; 

-- Extract a specific range of chars
SELECT job_title,         -- will show all data in the field
SUBSTR(job_title, 1, 10), -- will only show characters 1-10
SUBSTR(job_title, 11)     -- will show character 11 onwards
FROM jobs;

-- This will return the number of sales per job_title
SELECT job_title,
INSTR(job_title, 'Sales') AS Sales_Occur  
FROM jobs
ORDER BY Sales_Occur DESC;

-- this always for string literals to be added to the returned data
SELECT first_name || ', ' || last_name AS FullName
From employees;

SELECT 314.42325,
ROUND(314.42325, 2),  -- 314.42
ROUND(314.42325, 0),  -- 314
TRUNC(314.42325)      -- 314
FROM dual;

SELECT employee_id, first_name, last_name, salary AS Yearly,
ROUND(salary / 12), 2) AS Monthly 
FROM employees;

-- NVL will convert one value to another where stated by WHERE
SELECT employee_id, commission_pct,
NVL(NULL,0.2)
FROM employees
WHERE commission_pct IS NULL;

SELECT first_name, last_name, job_id, hire_date,
ROUND((SYSDATE - hire_date) / 365, 2) AS YearsTenure
FROM employees
ORDER BY YearsTenure DESC;

SELECT TO_CHAR(1210.73, '$9,999.00')
FROM dual;

SELECT TO_DATE('2010/04/30', 'yyyy/mm/dd')
FROM dual;
#+END_EXAMPLE



** CBT Nuggets Oracle Database 11g 1Z0-052
*** Lesson 3 - Preparing the DB Environment
- Oracle Planning Q's
  1. Which edition of Oracle
  2. System Requirements
  3. Prerequisite steps
     - os users, groups
     - FS, security, provisioning
       
- Oracle 11g Editions
  - Enterprise - max version
  - Standard   - <= 4 cpu sockets
      - supports RAC (real application clustering)
  - Std Ed One - <= 2 sockets $180/user (5min)
  - Express    - free, small footprint DB
    
- System Requirements
  - MS Windows(2003>), *Nix
    - 32bit
    - 64bit
  - 1GB RAM
  - VRAM/swap ---> double RAM
  - 5.2 GB disk space
    
- Optimal Flexible Arch (OFA)
  - makes it easier to manage multi inst/versions of Oracle DB
  - env variables
    - ORACLE_BASE - root of database package - /u01/app/oracle
    - ORACLE_HOME - root of 1 instance - /u01/app/oracle/product/11.1.0/dbname
      
- Oracle Universal Installer (OUI)
  - Java app ---> consistent interface
    - uses
      - installation
      - uninstallation
      - patching
      - upgrades
  
*** Lesson 4 - Creating an Oracle DB

DB Planning Questions
  - Storage
    - disk config, disk number, will RAID be used
    - how many data files
  - How many tablespaces?    
  - What data types will be stored?
  - Future growth possibility (Scaling)
  - Data access type?
    - OLTP (Oline Transaction Processing) - Short term frequent transactions
    - OLAP (Oline Analytical Processing)  - Data warehousing
  - Which character set? - shoulds I use unicode, will I require multiple languages (twice as much space)
    - difficult to change later after configuration
      
Database Config Assistant (DBCA)
  - Called from OUI or separately
  - Operations
    - Create DB
    - Config DB options
    - Delete DB
    - Manage templates
      - seed     - includes data files
      - non-seed - no data files
  
  - the DBCA can be found /app/oracle/product/11.2.0/dbhome/bin/
    - makesure that this is added to the path env variable
      
  - Defualt Users
    - SYS    - root, superuser account
    - SYSTEM - almost full control 
    - DBSNMP - used for snmp
    - SYSMAN - used for db management
      
Oracle DB Admin Tools
  - OUI and the OUI Inventory
  - DBCA
  - Enterprise Manager
    - DB Control
    - Grid Control
  - SQL*Plus
    - interactive or batch
  - SQL Developer ---> requires JRE
    
Other Tools
  - Navicat - http://navicat.com
  - TOAD - http://quest.com
    
* Books

* Links
http://orana.info/
