#+TAGS: db nosql cache web_cache machine_learning


* Redis
HomePage: [[https://redis.io/][redis.io]] 
* Cmds
- redis-cli

* Description
Redis is a key-value database which is often grouped under the NoSQL category of databases. It was initially released by the developer Salvatore Sanfilippo on the 10th of April 2009.

Redis is an in-memory database which means that it’s data is stored on its host’s RAM memory. This makes Redis blazingly fast because it does not have to wait for traditional hard drive seek and read times.

Being a NoSQL database, Redis allows you to create schema-less data structures that fit your applications needs. You can use Redis for simple things, like creating a visitor counter, or for more detailed information, such as storing user information.

* Usage
- installing Redis
#+BEGIN_SRC sh
add-apt-repository ppa:chris-lea/redis-server
apt-get update
apt-get install -y redis-server
#+END_SRC

** Data Types
- Strings - A string is a binary safe value that had a maximum length of 512 megabytes.
- Lists - A list of strings sorted by insertion order.
- Sets - A set is an unordered collection of strings.
- Hashes - A collection of key value pairs.
- Sorted Sets - Sorted sets are similar to the sets data types but each have a user defined score.
- Bitmaps - Bitmaps may also be known as bit arrays. Bitmaps are great for saving space when storing information.

** Operations
set - give a key a value
setnx - set a key:value pair only if not already set
get - get a key's value
del - delete a key:value pair
incr - increase value by one - it also ensures correct increment when two clients access the same value(by 2 not 1).
expr - expire sets when to kill a key
ttl 
  - this will tell you how long a key has to live
  - -1 means that the key will never expire
  - -2 means that the key doesn't exist
    
*** List
An key can be used as a list as long as it hasn't already be set as another data type
rpush - adds the value to the right of the current list
lpush - adds the value to the left of the current list
llen - number of values in list 
lrange - this will print the selected range 0 first value, -1 last value
lpop - pop value from the left
rpop - pop value from the right

*** Set
Similar to a list but has no ordering, and each element can only be used once
sadd - adds the element to the set
srem - removes the element from the set
sismember - tests if the element is in the set
smembers - returns a list of members of a set
sunion - combines 2 or more sets and returns the members

*** Sorted Set
These are similar to sets but each value has a score
> zadd key score value 
add value to sorted set
> zrange key 0 -1
print requested range, count uses score for order

*** Hash
map between string field and string value
> hset <key:value> <hash_key:hash_value>
set a hash key value pair to an object
> hgetall <key:value>
this will get all mappings for requested key
> hmset <key:value> <hash_key:hash_value> <hash_key:hash_value> <hash_key:hash_value> ...
this allows the setting of multiple mappings
> hget <key:value> hash_key
this will retrieve the value of the hash_key
hincrby - incresase hash value by x
hdel - delete a hash value

** Flush Redis Cache
Log into the redis CLI using the following:
#+BEGIN_SRC sh
redis-cli -p 6380
#+END_SRC

Then run flushall to flush all db's in redis:
#+BEGIN_SRC sh
127.0.0.1:6380> flushall
#+END_SRC

** Installing Extra Instances
URL: [[https://gist.github.com/jarvys/11393385][github multiple instances]]

* Lecture
* Tutorial
* Books
[[file://home/crito/Documents/Database/Redis/Learning_Redis.pdf][Learning Redis]]
[[file://home/crito/Documents/Database/Redis/Redis_Cookbook.pdf][Redis Cookbook]]
[[file://home/crito/Documents/Database/Redis/Redis_Essentials.pdf][Redis Essentials]]
[[file://home/crito/Documents/Database/Redis/Redis_in_Action.pdf][Redis in Action]]
* Links
[[https://redis.io/documentation][Redis Documentation]]
[[http://highscalability.com/blog/2014/9/8/how-twitter-uses-redis-to-scale-105tb-ram-39mm-qps-10000-ins.html][How Twitter Uses Redis to Scale]]
[[https://content.pivotal.io/blog/using-redis-at-pinterest-for-billions-of-relationships][Using Redis at Pinterest for Billions of Relationships]]
[[https://scaleyourcode.com/blog/article/25][How does CodePen use Redis? Critical and simple use cases, backups, and config tweaks]]
[[https://linuxacademy.com/cp/socialize/index/type/community_post/id/12599][Linux Academy - Introduction to Redis - Alex Braunton]]
