#+TAGS: awk column_manipulation


* awk
* Descripton
Aho, Weinberger and Kernighan

Awk is mostly used for pattern scanning and processing. It searches
files to see if they contain lines that matches with the specified
patterns and then perform associated actions.

Key features:

- Awk views a text file as records and fields

- it has variables, conditionals and loops

- arithmetic and string operators

- it can generate formatted reports

* Usage

> awk '<pattern>' {<action>} file

+ Awk working methodology

1) awk reads the input files one line at a time

2) for each line, it matches with given pattern in the given order, if matches perform the corresponding action.

3) if no pattern matches, no action will be performed.

4) in the above syntax either search pattern or action are optional, but not both.

5) if the search pattern is not given then awk performs the given action on every line.

6) if the action is not given, print all the lines that match with the given pattern.

7) empty braces without any action does nothing.

8) each statement in actions should be delimited with a semicolon.

** Print every line
#+BEGIN_SRC sh
> awk '{print;}' file.txt
#+END_SRC

** Print lines that match a pattern
#+BEGIN_SRC sh
awk '/pattern/' <file>
#+END_SRC
the forward slashes are needed

- cut second column of ps aux
#+BEGIN_SRC sh
ps aux | awk '{ print $2 }'
#+END_SRC

** Print only specific fields
#+BEGIN_SRC sh
awk '{print $x $y;}' file.txt
#+END_SRC
this will only print field x and filed y. counting with awk starts with 1 not 0.

- Initialisation and final action
These are specified with the keywords BEGIN and END

syntax:

BEGIN { Actions }

{ ACTION } # Action for every line in a file

END { Actons }

** Print how many lines are in a file
#+BEGIN_SRC sh
awk 'BEGIN { count = 0; } { print; } { count++; } END { print count; }'
#+END_SRC

** Setting the delimiter
#+BEGIN_SRC sh
awk -F":" { print $1; } access.log
#+END_SRC

** Print first line instance and keep order
#+BEGIN_SRC sh
awk '!seen[$0]++' file.txt
#+END_SRC

* Lecture
* Tutorial
* Books
file://home/crito/Documents/Tools/Effective_awk_Programming_4ed.pdf
* Links
