
#+TAGS: sys op


* date								     :sys:op:
* Description
This command allows the setting of the date or provides the time.
* Usage
** Show the date and time

> date

<day> <date> <month> <HH:MM:SS> <time\_zone> <YYYY>

* Find the day of a certain date
#+BEGIN_SRC sh
date --date="03/08/2019"
#+END_SRC
or
#+BEGIN_SRC sh
date --date="2 Feb 2018"
#+END_SRC
or
#+BEGIN_SRC sh
date --date="Feb 2 2014"
#+END_SRC

** Read date patterns from a file using --file option
This is similar to the above but allows for multiple queries. The file
has a date on each line.

> date --file=<file>

* Using relative date
#+BEGIN_SRC sh
date --date="next <string>"
#+END_SRC

mon-sun, month, year

** Seconds since the epoch

If --date=@x is used, it converts x number of seconds since the epoch
(1970-01-01 UTC) to a date.

> date --date=@x

> date --date=@10

*Display past date*

> date --date='<relative date>

examples:

> date --date='3 seconds ago'

> date --date='1 day ago'

> date --date='yesterday'

> date --date='1 month ago'

> date --date='1 year ago'

** Set date and time

> date -s "<day> <month> <date> <HH:MM:SS> <time\_zone> <YYYY>"

-s or --set 

*Display universal time (UTC)*

> date -u

*View the last modification time for a file*

> date -r <file>
* Lecture
* Tutorial
* Books
* Links
