#+TAGS: net sec_d fw fwd


* firewalld						   :net:sec_d:fw:fwd:
HomePage: [[http://www.firewalld.org/][firewalld.org]]
* Cmds
[[file://home/crito/org/tech/cmds/firewall-config.org][firewall-config]]
[[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]]
* Files
/usr/lib/firewalld/services - this directory houses all the services files (xml)
/etc/firewalld/services - this directory is where you add your own service files
/etc/firewalld/firewalld.conf

* Description
* Usage
The [[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]] is generally used for administration
Gui front-end is called [[file://home/crito/org/tech/cmds/firewall-config.org][firewall-config]]
** Zones
*** Block  
Any incoming network connections are rejected with an icmp-host-prohibited message for IPv4 and icmp6-adm-prohibited for IPv6. Only network connections initiated within this system are possible.
*** DMZ 
For computers in your demilitarized zone that are publicly-accessible with limited access to your internal network. Only selected incoming connections are accepted.
*** Drop
Any incoming network packets are dropped, there is no reply. Only outgoing network connections are possible.
*** External
For use on external networks with masquerading enabled especially for routers. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
*** Home
For use in home areas. You mostly trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
*** Internal
For use on internal networks. You mostly trust the other computers on the networks to not harm your computer. Only selected incoming connections are accepted.
*** Public
For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
*** Trusted
All network connections are accepted.
*** Work
For use in work areas. You mostly trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
** Creating Services files
First copy a service file from /usr/lib/firewalld/services/ to use as a template

- ldap.xml
#+BEGIN_EXAMPLE
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>LDAP</short>
  <description>Lightweight Directory Access Protocol (LDAP) server</description>
  <port protocol="tcp" port="389"/>
</service>
#+END_EXAMPLE
replace the fileds with the new details

* Lecture
* Tutorial
* Books
* Links
