#+TAGS: firewalld security fw


* firewalld
HomePage: [[http://www.firewalld.org/][firewalld.org]]
RHEL Docs: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_firewalls
* Cmds
[[file://home/crito/org/tech/cmds/firewall-config.org][firewall-config]]
[[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]]

** RHEL7
- iptables - this cmds is still available, it is symbolicly linked to /usr/sbin/xtables-multi 

* Files
/usr/lib/firewalld/services - this directory houses all the services files (xml)
/etc/firewalld/services - this directory is where you add your own service files
/etc/firewalld/firewalld.conf
** RHEL7
/etc/sysconfig/iptables-config
/etc/sysconfig/ip6tables-config

* Description
* Usage
The [[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]] is generally used for administration
Gui front-end is called [[file://home/crito/org/tech/cmds/firewall-config.org][firewall-config]]

- view the current default zone
#+BEGIN_SRC sh
firewall-cmd --get-default
#+END_SRC

- view the current rules in place
#+BEGIN_SRC sh
firewall-cmd --list-all
#+END_SRC
the services will list what is currently enabled

- view the rules for another zone
#+BEGIN_SRC sh
firewall-cmd --zone=home --list-all
#+END_SRC
this will list the available services that would be enabled if that zone were to be used

- add a source ip to a zone
#+BEGIN_SRC sh
firewall-cmd --zone=home --add-source=192.168.1.0/24
#+END_SRC
this will now apply the rules set for that zone to machines that fit this ip block

- make a change permanent
#+BEGIN_SRC sh
firewall-cmd --zone=home --permanent --add-source=192.168.1.0/24
firewall-cmd --reload
#+END_SRC
the reload is always required with a permanent rule
this will mean that the change will be persistant at the next reboot, or service reload

- reload the firewalld serrvice
#+BEGIN_SRC sh
firewall-cmd --reload
#+END_SRC

- adding an open port to a zone
#+BEGIN_SRC sh
firewall-cmd --zone=public --add-port=80/tcp
#+END_SRC
this would open port 80, but only until the next reload

-adding a service to be available
#+BEGIN_SRC sh
firewall-cmd --zone=public --add-service=http
#+END_SRC

- close all ports and services, access only available in front of the machine
#+BEGIN_SRC sh
firewall-cmd --panic
#+END_SRC
runtime change only


** Zones
- These are the basic units used to group rules. 
- An interface is assigned a zone, and this dictates the behaviour that the fw should allow.
- These zones allow flexibility for machines that move between networks (i.e. laptops).

- Drop
Any incoming network packets are dropped, there is no reply. Only outgoing network connections are possible.
- Block  
Any incoming network connections are rejected with an icmp-host-prohibited message for IPv4 and icmp6-adm-prohibited for IPv6. Only network connections initiated within this system are possible.
- Public
For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
- External
For use on external networks with masquerading enabled especially for routers. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
- Internal
For use on internal networks. You mostly trust the other computers on the networks to not harm your computer. Only selected incoming connections are accepted.
- DMZ 
For computers in your demilitarized zone that are publicly-accessible with limited access to your internal network. Only selected incoming connections are accepted.
- Work
For use in work areas. You mostly trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
- Home
For use in home areas. You mostly trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
- Trusted
All network connections are accepted.

*** Pre-defined Zones (least trusted to most trusted)
drop - All incoming connections are dropped without reply and only outgoing connections are possible.
block - Similar to the above, but instead of simply dropping connections, incoming requests are rejected with an icmp-host-prohibited or icmp6-adm-prohibited message.
public - Represents public, untrusted networks. You don't trust other computers but may allow selected incoming connections on a case-by-case basis.
external - External networks in the event that you are using the firewall as your gateway. It is configured for NAT masquerading so that your internal network remains private but reachable.
internal - The other side of the external zone, used for the internal portion of a gateway. The computers are fairly trustworthy and some additional services are available.
dmz - Used for computers located in a DMZ (isolated computers that will not have access to the rest of your network). Only certain incoming connections are allowed.
work - Used for work machines. Trust most of the computers in the network. A few more services might be allowed.
home - A home environment. It generally implies that you trust most of the other computers and that a few more services will be accepted.
trusted - Trust all of the machines in the network. The most open of the available options and should be used sparingly.

** Creating Services files
First copy a service file from /usr/lib/firewalld/services/ to use as a template

- ldap.xml
#+BEGIN_EXAMPLE
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>LDAP</short>
  <description>Lightweight Directory Access Protocol (LDAP) server</description>
  <port protocol="tcp" port="389"/>
</service>
#+END_EXAMPLE
replace the fileds with the new details

** Internal Port Forwarding RHEL7

- Login to the root account
#+BEGIN_SRC sh
su -
#+END_SRC

- Install firewalld
#+BEGIN_SRC sh
yum install -y firewalld
#+END_SRC

- enable and start firewalld
#+BEGIN_SRC sh
systemctl enable firewalld
systemctl start firewalld
#+END_SRC

- add rule to allow port 22 for ssh
#+BEGIN_SRC sh
firewall-cmd --permanent --add-port=22/tcp
#+END_SRC

- add rule to forward port 443 to port 5901
#+BEGIN_SRC sh
firewall-cmd --permanent --add-forward-port=port=443:proto=tcp:toport=5901
#+END_SRC

- reload the firewall
#+BEGIN_SRC sh
firewall-cmd --reload
#+END_SRC

* Lecture
* Tutorial
** Security with firewalld
Guide: [[file://home/crito/Documents/Linux/Labs/security-with-firewalld-labs.pdf][Red Hat Security with FirewallD]]
* Books
* Links
[[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_firewalls][Using Firewalls - RHEL7 Docs]]
