#+TAGS: firewalld security fw


* firewalld
HomePage: [[http://www.firewalld.org/][firewalld.org]]
* Cmds
[[file://home/crito/org/tech/cmds/firewall-config.org][firewall-config]]
[[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]]

** RHEL7
- iptables - this cmds is still available, it is symbolicly linked to /usr/sbin/xtables-multi 

* Files
/usr/lib/firewalld/services - this directory houses all the services files (xml)
/etc/firewalld/services - this directory is where you add your own service files
/etc/firewalld/firewalld.conf
** RHEL7
/etc/sysconfig/iptables-config
/etc/sysconfig/ip6tables-config

* Description
* Usage
The [[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]] is generally used for administration
Gui front-end is called [[file://home/crito/org/tech/cmds/firewall-config.org][firewall-config]]
** Zones
*** Block  
Any incoming network connections are rejected with an icmp-host-prohibited message for IPv4 and icmp6-adm-prohibited for IPv6. Only network connections initiated within this system are possible.
*** DMZ 
For computers in your demilitarized zone that are publicly-accessible with limited access to your internal network. Only selected incoming connections are accepted.
*** Drop
Any incoming network packets are dropped, there is no reply. Only outgoing network connections are possible.
*** External
For use on external networks with masquerading enabled especially for routers. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
*** Home
For use in home areas. You mostly trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
*** Internal
For use on internal networks. You mostly trust the other computers on the networks to not harm your computer. Only selected incoming connections are accepted.
*** Public
For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
*** Trusted
All network connections are accepted.
*** Work
For use in work areas. You mostly trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.
** Creating Services files
First copy a service file from /usr/lib/firewalld/services/ to use as a template

- ldap.xml
#+BEGIN_EXAMPLE
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>LDAP</short>
  <description>Lightweight Directory Access Protocol (LDAP) server</description>
  <port protocol="tcp" port="389"/>
</service>
#+END_EXAMPLE
replace the fileds with the new details

** Internal Port Forwarding
*** Red Hat/CentOS 7 use firewalld as the default firewall application:

- Login to the root account
#+BEGIN_SRC sh
su -
#+END_SRC

- Install firewalld
#+BEGIN_SRC sh
yum install -y firewalld
#+END_SRC

- enable and start firewalld
#+BEGIN_SRC sh
systemctl enable firewalld
systemctl start firewalld
#+END_SRC

- add rule to allow port 22 for ssh
#+BEGIN_SRC sh
firewall-cmd --permanent --add-port=22/tcp
#+END_SRC

- add rule to forward port 443 to port 5901
#+BEGIN_SRC sh
firewall-cmd --permanent --add-forward-port=port=443:proto=tcp:toport=5901
#+END_SRC

- reload the firewall
#+BEGIN_SRC sh
firewall-cmd --reload
#+END_SRC

*** Ubuntu*/Debian systems can use ufw as a firewall for port redirection: 
- Login to the root account
#+BEGIN_SRC sh
su -
#+END_SRC

- Make sure ufw is installed and enabled
#+BEGIN_SRC sh
apt-get install -y ufw
update-rc.d ufw enable
service ufw start
#+END_SRC

- Edit the /etc/ufw/before.rules. Add the below lines to the top of the file and save the file
#+BEGIN_EXAMPLE
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 5901
COMMIT
#+END_EXAMPLE

- Allow connections on the needed ports in ufw (note 22 is for ssh and just included so you can ssh back to the server)
#+BEGIN_SRC sh
ufw allow 22
ufw allow 443
ufw allow 5901
#+END_SRC

- Enable ufw
#+BEGIN_SRC sh
ufw enable
#+END_SRC

- Reboot the server

** 
* Lecture
* Tutorial
* Books
* Links
[[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_firewalls][Using Firewalls - RHEL7 Docs]]
