#+TAGS: sys anal sysstat


* pidstat						   :sys:anal:sysstat:
* Description
The pidstat command is used for monitoring individual tasks currently being managed by the Linux kernel. It writes to standard output activities for every task selected with option -p or for every task managed by the Linux kernel if option -p ALL has been used. Not selecting any tasks is equivalent to specifying -p ALL but only active tasks (tasks with non-zero statistics values) will appear in the report.
The pidstat command can also be used for monitoring the child processes of selected tasks. Read about option -T below.

* Usage
#+BEGIN_EXAMPLE
$ pidstat <options> <pid> <interval> <num_to_print>
#+END_EXAMPLE

- Options
p <pid> - specify pid to monitor
C <name> - specify process name 
d - report i/o statistics
l - display process name and arguments
t - print in tree format

** Report task switching activity
#+BEGIN_SRC sh
pidstat -w -p 3446 2 5
#+END_SRC
this will monitor pid 3446 and report every 2 seconds for 5 intervals

* Lecture
* Tutorial
* Books
* Links
