#+TAGS: sys anal sysstat


* sar							   :sys:anal:sysstat:
HomePage: [[http://sebastien.godard.pagesperso-orange.fr/][sebastien.godard.fr/sysstat]]
Github: [[https://github.com/sysstat/sysstat][github.com/sysstat]]
* Description
The sar command writes to standard output the contents of selected cumulative activity counters in the operating system. The accounting system, based on the values in the count and interval parameters, writes information the specified number of times spaced at the specified intervals in seconds. 

* Setup
These two files have to be changed for sar to be used

/etc/default/sysstat # Should sadc collect system activity informations?
Valid values # are "true" and "false". Please do not put other values,
they # will be overwritten by debconf! ENABLED="true"

/etc/cron.d/sysstat Change 5-55/10 * * * * root command -v debian-sa1 >
/dev/null && debian-sa1 1 1 To //2 / * * * root command -v debian-sa1 >
/dev/null && debian-sa1 1 1
* Usage
* Lecture
* Tutorial
* Books
* Links
