


* Description							    :Network:
Traceroute uses the TTL field to determine the distance between the host
and the target. It does this by initially sending the first packet with
a TTL of 1 which is discarded by the first hop router which sends back
to the source ip an ICMP error message of "Time exceeded".

* Basic usage

> traceroute <ipaddress>

or

> traceroute <domain.com>

The '*' field

This means that the required feild could not be fetched. The reason
could anything from reverse DNS lookup failure to packets not hitting
the target router, to packets getting lost on the way back. We can not
determine exactly what caused the *.

+ Disable IP address and host name mapping

> traceroute <ipaddress> -n

+ Configure response wait time

The time the utility waits after issuing a probe can be configured using
the -w flag.

> traceroute <ipaddress> -w <seconds>

+ Configure number of queries per hop

Traceroute uses 3 packets per hop by default. This can be changed with
the -q flag.

> traceroute <ipaddress> -q <packets>

+ Configure the TTL value to start with

> traceroute <ipaddress> -f <ttl>

the default is 1, changing this will determine which hop the traceroute
starts from. 

* Links
