#+TAGS: sec_d fw


* ufw
Wiki: [[https://wiki.ubuntu.com/UncomplicatedFirewall][wiki.ubuntu.com/ufw]]
* Description
UFW, or Uncomplicated Firewall, is an interface to iptables that is geared towards simplifying the process of configuring a firewall.
* Usage
- deny all incoming
#+BEGIN_SRC sh
ufw default deny incoming
#+END_SRC

- allow all outgoing
#+BEGIN_SRC sh
ufw default allow outgoing
#+END_SRC

** Allowing certain services
ufw uses the /etc/services directory to determine port nubmers
- allow ssh
#+BEGIN_SRC sh
ufw allow ssh
#+END_SRC
it knows that ssh is port 22 as it is set in /etc/services

** Enable the Firewall
#+BEGIN_SRC hs
ufw enable
#+END_SRC

** Disabling the Firewall
#+BEGIN_SRC sh
ufw disable
#+END_SRC
** Restart the Firewall
#+BEGIN_SRC sh
ufw reset
#+END_SRC
** View current Status and set Rules
- active
#+BEGIN_SRC sh
ufw status verbose
#+END_SRC

- inactive
#+BEGIN_SRC sh
grep '^### tuple' /lib/ufw/user*.rules
#+END_SRC
** Allow connections from specific ip
#+BEGIN_SRC sh
ufw allow from 15.51.51.111
#+END_SRC
- set specfic ip and service
#+BEGIN_SRC sh
ufw allow from 15.51.51.111 to any port 22
#+END_SRC

** Allow connections from a subnet
#+BEGIN_SRC sh
ufw allow from 15.51.51.0/24
#+END_SRC
- set block and service
#+BEGIN_SRC sh
ufw allow from 15.51.51.0/24 to any port 22
#+END_SRC

** Allowing connections over specific interface
#+BEGIN_SRC sh
ufw allow in on eth0 to any port 80
#+END_SRC
this would open port 80 to the public
** Denying connections from specific ip
#+BEGIN_SRC sh
ufw deny from 15.51.51.111
#+END_SRC
** Denying a specfic service if set to allow all incoming
#+BEGIN_SRC sh
ufw deny from http
#+END_SRC
** Deleting specific rules
#+BEGIN_SRC sh
ufw status numbered
ufw delete 2
#+END_SRC
   
- delete actual rule
#+BEGIN_SRC sh
ufw delete allow http
#+END_SRC
** Ubuntu*/Debian systems can use ufw as a firewall for port redirection: 
- Login to the root account
#+BEGIN_SRC sh
su -
#+END_SRC

- Make sure ufw is installed and enabled
#+BEGIN_SRC sh
apt-get install -y ufw
update-rc.d ufw enable
service ufw start
#+END_SRC

- Edit the /etc/ufw/before.rules. Add the below lines to the top of the file and save the file
#+BEGIN_EXAMPLE
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 5901
COMMIT
#+END_EXAMPLE

- Allow connections on the needed ports in ufw (note 22 is for ssh and just included so you can ssh back to the server)
#+BEGIN_SRC sh
ufw allow 22
ufw allow 443
ufw allow 5901
#+END_SRC

- Enable ufw
#+BEGIN_SRC sh
ufw enable
#+END_SRC

- Reboot the server

**** Rule Permanence
- Altered rules will take effect immediately, but on reboot will revert to originally set rules.
- The --permanent flag will push the rule to the non-ephemeral firewall. This rule will then be activeated on the next reboot.

* Lecture
* Tutorial
* Books
* Links
