#+TAGS: umask file_priviliges shell_builtin


* umask
* File
/etc/profile - this is the usual place where umask is set
* Description
Set the shell process’s file creation mask to mode. If mode begins with a digit, it is interpreted as an octal number; if not, it is interpreted as a symbolic mode mask similar to that accepted by the chmod command. If mode is omitted, the current value of the mask is printed. If the -S option is supplied without a mode argument, the mask is printed in a symbolic format. If the -p option is supplied, and mode is omitted, the output is in a form that may be reused as input. The return status is zero if the mode is successfully changed or if no mode argument is supplied, and non-zero otherwise.

* Usage
** Display the current mask
> umask
022

** Octal codes
0 - any permissions may be set
1 - setting of execute permission is prohibited
2 -  setting of write permission is prohibited
3 - setting of write and execute permission is prohibited
4 - setting of read permission is prohibited
5 - setting of read and execute permission is prohibited
6 - setting of read and write permission is prohibited
7 - all permissions are prohibited from being set

** View the umask with symbolic notation
> umask -S
u=rwx,g=rx,o=rx

* Lecture
* Tutorial
* Books
* Links


