#+TAGS: user_add add_user useradd


* useradd
* Files
/etc/default/useradd - this sets the defaults for new users
/etc/login.defs      - this file also specifies defaults for new users
/etc/skel/           - this directory contains all the files a new users home directroy will have automatically created
/etc/group           - this file contains all the groups created on the system, along with who is apart of each group
/etc/gshadow         - contains shadow information for the group accounts

* Description
* Usage
> useradd <login>

This creates a normal user issues a uid, gid, but no home directory is created ( but is set in the /etc/passwd ). Shell is set from the default settings. No password is set and the user is unable to login until one is set. Once a password is set the user can now login, but will enter at /home (this is set in useradd default), until the home directory is created.

- View current useradd defaults
#+BEGIN_SRC sh
useradd -D
#+END_SRC

** Create a new user
#+BEGIN_SRC sh
useradd -m -d /home/testuser testuser
#+END_SRC
m - create home directory
d - define home directory
- Password is required for account to be activated
- The home directory has to be created manually
  - this directory will be bare to provide the base file copy the /etc/skel to the new directory
    
- adding the skeleton files during creation
#+BEGIN_SRC sh
useradd newuser -m -k /etc/skel -u 1010 -g 1010 -G 100 -s /bin/zsh
#+END_SRC
k - specify the skeleton file
u - set a specific uid
g - set the gid(this should only be used if the group has alread been created, otherwise omit and it will be created with the -u flag)
G - add addtional groups
s - set the shell

** Configure a user with custom settings

> useradd -s <shell> -m -d <home dir> -g <group> UserName

s - shell
m - create users home directory if it doesn't already exist
d - home directory of the user
g - group name
G - group names

UserName - Login id

- Adding new user to group?
#+BEGIN_SRC sh
useradd -G admins,ftp,www,developers jerry
#+END_SRC
this only works with new users

- Add a comment

* Lecture
* Tutorial
* Books
* Links

