#+TAGS: bind dns bind9


* BIND
* Files
/etc/bind - this holds all the configuration files
/etc/bind/named.conf.options - this files has options such as setting forwarding dns servers
/etc/bind/named.conf.local   - this is where we configure the base zones
** named.conf - this file is the main configration file for BIND
*** This is the secure named.conf file from cymru.com
#+BEGIN_EXAMPLE
// @(#)named.conf 02 OCT 2001 Team Cymru noc@cymru.com 
// Set up our ACLs 
// In BIND 8, ACL names with quotes were treated as different from 
// the same name without quotes. In BIND 9, both are treated as 
// the same. 
acl "xfer" { 
    none;   // Allow no transfers.  If we have other 
            // name servers, place them here. 
            
};

acl "trusted" {


// Place our internal and DMZ subnets in here so that 
// intranet and DMZ clients may send DNS queries.  This 
// also prevents outside hosts from using our name server 
// as a resolver for other domains. 
192.168.1.0/24; 
localhost;

};

logging {


channel default_syslog {
// Send most of the named messages to syslog. 
syslog local2; 
severity debug;

}; 

channel audit_log {
// Send the security related messages to a separate file. 
file "/var/named/bind/named.log"; 
severity debug; 
print-time yes;

}; 

category default { default_syslog; }; 
category general { default_syslog; }; 
category security { audit_log; default_syslog; }; 
category config { default_syslog; }; 
category resolver { audit_log; }; 
category xfer-in { audit_log; }; 
category xfer-out { audit_log; }; 
category notify { audit_log; }; 
category client { audit_log; }; 
category network { audit_log; }; 
category update { audit_log; }; 
category queries { audit_log; }; 
category lame-servers { audit_log; };

};
// Set options for security 
options { 
    directory "/var/named"; 
    pid-file "/var/named/named.pid"; 
    statistics-file "/var/named/named.stats"; 
    memstatistics-file "/var/named/named.memstats"; 
    dump-file "/var/adm/named.dump"; 
    zone-statistics yes;

    // Prevent DoS attacks by generating bogus zone transfer 
    // requests.  This will result in slower updates to the 
    // slave servers (e.g. they will await the poll interval 
    // before checking for updates). 
    notify no;

            // Generate more efficient zone transfers.  This will place 
    // multiple DNS records in a DNS message, instead of one per 
    // DNS message. 
    transfer-format many-answers;

    // Set the maximum zone transfer time to something more 
    // reasonable.  In this case, we state that any zone transfer 
    // that takes longer than 60 minutes is unlikely to ever 
    // complete.  WARNING:  If you have very large zone files, 
    // adjust this to fit your requirements. 
    max-transfer-time-in 60;

    // We have no dynamic interfaces, so BIND shouldn't need to 
    // poll for interface state {UP|DOWN}. 
    interface-interval 0;

    allow-transfer { 
        // Zone tranfers limited to members of the 
        // "xfer" ACL. 
        xfer; 
    };

    allow-query { 
        // Accept queries from our "trusted" ACL.  We will 
        // allow anyone to query our master zones below. 
        // This prevents us from becoming a free DNS server 
        // to the masses. 
        trusted; 
    };

    allow-query-cache { 
        // Accept queries of our cache from our "trusted" ACL.  
        trusted; 
    }; 
};


view "internal-in" in { 
    // Our internal (trusted) view. We permit the internal networks 
    // to freely access this view. We perform recursion for our 
    // internal hosts, and retrieve data from the cache for them.

    match-clients { trusted; }; 
    recursion yes; 
    additional-from-auth yes; 
    additional-from-cache yes;

zone "." in { 
    // Link in the root server hint file. 
    type hint; 
    file "db.cache"; 
};

zone "0.0.127.in-addr.arpa" in { 
    // Allow queries for the 127/8 network, but not zone transfers. 
    // Every name server, both slave and master, will be a master 
    // for this zone. 
    type master; 
    file "master/db.127.0.0";

    allow-query { 
        any; 
    };

    allow-transfer { 
        none; 
    }; 
};

zone "localhost" {
   type master;
   file "db.localhost";
    allow-query { 
        any; 
    };

    allow-transfer { 
        none;
   };
};

zone "internal.example.com" in { 
    // Our internal A RR zone. There may be several of these. 
    type master; 
    file "master/db.internal"; 
};

zone "1.168.192.in-addr.arpa" in { 
    // Our internal PTR RR zone. Again, there may be several of these. 
    type master; 
    file "master/db.192.168.1"; 
};


};
// Create a view for external DNS clients. 
view "external-in" in { 
    // Our external (untrusted) view. We permit any client to access 
    // portions of this view. We do not perform recursion or cache 
    // access for hosts using this view.

    match-clients { any; }; 
    recursion no; 
    additional-from-auth no; 
    additional-from-cache no;

// Link in our zones 
zone "." in { 
    type hint; 
    file "db.cache"; 
};
zone "example.net" in { 
    type master; 
    file "master/db.example";

    allow-query { 
        any; 
    }; 
};

zone "1.1.10.in-addr.arpa" in { 
    type master; 
    file "master/db.10.1.1";

    allow-query { 
        any; 
    }; 
};


};
// Create a view for all clients perusing the CHAOS class.
// We allow internal hosts to query our version number.
// This is a good idea from a support point of view.
view "external-chaos" chaos { 
    match-clients { any; }; 
    recursion no;

    zone "." { 
        type hint; 
        file "/dev/null"; 
    };

    zone "bind" { 
        type master; 
        file "master/db.bind";

        allow-query { 
            trusted; 
        }; 
        allow-transfer { 
            none; 
        }; 
    };


};
The db.bind zone file

The db.bind zone file is used to track miscreants who attempt to query the CHAOS TXT records version.bind and authors.bind.  You can also use this zone file to change the strings returned by such queries.  Using the "version" directive in the options stanza will block the version.bind query, but it will not log such attempts.
; @(#)db.bind v1.2 25 JAN 2001 Team Cymru Thomas noc@cymru.com 
; 
$TTL    1D 
$ORIGIN bind. 
@       1D      CHAOS   SOA     localhost. root.localhost. ( 
                2001013101      ; serial 
                3H              ; refresh 
                1H              ; retry 
                1W              ; expiry 
                1D )            ; minimum 
        CHAOS NS        localhost.

version.bind.   CHAOS  TXT "BIND 9.1.3+robhacks" 
authors.bind.   CHAOS  TXT "are better coders than I. :)" 
#+END_EXAMPLE

* Cmds
named-checkzone - this will check zone file syntax for errors
- [[file://home/crito/org/tech/cmds/rndc.org][rndc]]

* Description
* Usage
** Configure a Caching-Only Name Server - RHEL7
- install bind and it's utils
#+BEGIN_SRC sh
yum install -y bind bind-utils
#+END_SRC

- edit the /etc/named.conf
  - listen-on port 53
  - allow-query
  - dnssec-validation
#+BEGIN_EXAMPLE
options {
        listen-on port 53 { any; }; // edited from 127.0.0.1 to any
        listen-on-v6 port 53 { ::1; };
        directory       "/var/named";
        dump-file       "/var/named/data/cache_dump.db";
        statistics-file "/var/named/data/named_stats.txt";
        memstatistics-file "/var/named/data/named_mem_stats.txt";
        allow-query     { any; }; // edited from localhost to any
	// allow-query { any; !172.63.0.0/24; } this would allow anyone but the 172.63.0.0/24 network to query the server

        /* 
         - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
         - If you are building a RECURSIVE (caching) DNS server, you need to enable 
           recursion. 
         - If your recursive DNS server has a public IP address, you MUST enable access 
           control to limit queries to your legitimate users. Failing to do so will
           cause your server to become part of large scale DNS amplification 
           attacks. Implementing BCP38 within your network would greatly
           reduce such attack surface 
        */
        recursion yes;

        dnssec-enable yes;
        dnssec-validation no; //edited from yes to no

        /* Path to ISC DLV key */
        bindkeys-file "/etc/named.iscdlv.key";

        managed-keys-directory "/var/named/dynamic";

        pid-file "/run/named/named.pid";
        session-keyfile "/run/named/session.key";
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic; // level of logging
        };
};

zone "." IN {
        type hint;
        file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
#+END_EXAMPLE

- check the configuration
#+BEGIN_SRC sh
named-checkconf
#+END_SRC

- add the firewall rules
#+BEGIN_SRC sh
firewall-cmd --permanent --add-service=dns
firewall-cmd --reload
#+END_SRC

- start and enable the dns service
#+BEGIN_SRC sh
systemctl start named
systemctl enable named
#+END_SRC

- check that the caching name server is working
#+BEGIN_SRC sh
nslookup linuxacademy.com 127.0.0.1
#+END_SRC
if no output is produced that means that the dns isn't working correctly

** Install and Configure a Caching-Only Name Server - RHEL7 (LA LPIC2)
   
- install the required pkgs
#+BEGIN_SRC sh
yum -y install bind-utils bind
#+END_SRC

- start the service and enable
#+BEGIN_SRC sh
systemctl start named
systemctl enable named
systemctl status named
#+END_SRC

- configure the rndc.conf
#+BEGIN_SRC sh
rndc-confgen -r /dev/urandom -a
#+END_SRC
a random seed is required for the key to be created
  
- this will then need to be added to the /etc/named.conf
#+BEGIN_SRC sh
zone "." IN {
        type hint;
        file "named.ca";
};

key "rndc-key" {
      algorithm hmac-md5;
      secret "U7/L4YKs4Fg4wQ8eL5IKmg==";
};

controls {
      inet 127.0.0.1 port 953
              allow { 127.0.0.1; } keys { "rndc-key"; };
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
#+END_SRC

- the rndc.conf has to be changed to the named group
#+BEGIN_SRC sh
chgrp named /etc/rndc.conf
#+END_SRC

- the key by default will allow read access to all this need to be changed
#+BEGIN_SRC sh
chmod 640
#+END_SRC

- restart the named service and the new key should be available 
#+BEGIN_SRC sh
systemctl restart named
#+END_SRC

- confirm that you can connect to the named server
#+BEGIN_SRC sh
rndc status
#+END_SRC

- you may get an error indicating that an /etc/rndc.key is present but the /etc/rndc.conf is being used. If this occurs just delete the rndc.key
#+BEGIN_SRC sh
rm /etc/rndc.key
#+END_SRC

** Install and Configure a Name Server - RHEL7

- install the required pkgs
#+BEGIN_SRC sh
yum -y install bind-utils bind
#+END_SRC

- start the service and enable
#+BEGIN_SRC sh
systemctl start named
systemctl enable named
systemctl status named
#+END_SRC

- check that the rndc key entry is in the /etc/named.conf
#+BEGIN_SRC sh
less /etc/named.conf
#+END_SRC

- add the domain forward and reverse zone files to /etc/named.conf
#+BEGIN_EXAMPLE
zone "mydomain.com" {
	type master;
	file "fwd.mydomain.com.db"; //forward lookup zone database file
	allow-update { none; }; // this is where you would specify the server the update would come from
};

zone "25.31.172.in-addr.arpa" {
	type master;
	file "25.31.172.db"; // reverse lookkup zone database file
	allow-update { none; }; // this is where you would specify the server the update would come from
};

// how a slave would be added
zone "mydomain.com" {
	type slave;
	masters { 172.31.44.88; }; //this is the master node ip-addr
	file "fwd.mydomain.com.db";
};
#+END_EXAMPLE

- create the forward zone file
/var/named/fwd.mydomain.com.db
#+BEGIN_EXAMPLE
$TTL 86400
@	IN	SOA	named.mydomain.com.	root.mydomain.com. (
				10030			;Serial
				3600			;Refresh
				1800			;Retry
				604800			;Expire
				86400			;Minimum TTL
)
; Name Server
@	IN	NS	named.mydomain.com.
; A Record Definitions
named	IN	A	172.31.25.190
mailprod	IN	A	172.31.25.30
mailbkup	IN	A	172.31.25.31
; Canonical Name/Alias
dns	IN	CNAME	named.mydomain.com.
; Mail Exchange Records
@	IN	MX	10	mailprod.mydomain.com.
@	IN	MX	20	mailbkup.mydomain.com.
#+END_EXAMPLE

- create the reverse zone file
/var/named/25.31.172.db
#+BEGIN_EXAMPLE
$TTL 86400
@	IN	SOA	named.mydomain.com.	root.mydomain.com. (
				10030			;Serial
				3600			;Refresh
				1800			;Retry
				604800			;Expire
				86400			;Minimum TTL
)
; Name Server
@	IN	NS	named.mydomain.com.
; Pointer Records
172.31.25.190	IN	PTR	named.mydomain.com.
;190	IN	PTR	named.mydomain.com. this is the same as above, but using relative octet
30	IN	PTR	mailprod.mydomain.com.
31	IN	PTR	mailbkup.mydomain.com.
#+END_EXAMPLE

- test that the configurations are formatted correctly
#+BEGIN_SRC sh
named-checkconf
#+END_SRC
no output indicates no configuration syntax errors

- check that the zone files are correctly configured
#+BEGIN_SRC sh
named-checkzone mydomain.com fwd.mydomain.com.db
named-checkzone 25.31.172.in-addr.arpa 25.31.172.db
#+END_SRC
this will indicate if all is "OK"

- restart the named service for the changes to take effect
#+BEGIN_SRC sh
systemctl restart named
#+END_SRC

- test he named by checking named.mydomain.com
#+BEGIN_SRC sh
dig @localhoost named.mydomain.com
#+END_SRC
@ - this specifies to dig what name server to use

** Running BIND in a Chroot Jail (LA LPIC2 this is not complete, it doesn't run the jail when configured(video is incorrect))
   
- stop the named service
#+BEGIN_SRC sh
systemctl stop named
#+END_SRC

- edit the named configuration file telling the named service where to start
/etc/sysconfig/named
#+BEGIN_EXAMPLE
-t /chroot/named
#+END_EXAMPLE
this needs to be added at the end

- create the /chroot dir
#+BEGIN_SRC sh
mkdir -p /chroot/named/{dev,etc}
mkdir -p /chroot/named/var/{named,run}
#+END_SRC

- copy the configuration files to the jail
#+BEGIN_SRC sh
cp /etc/named.conf /chroot/named/etc
cp /etc/localtime /chroot/named/etc
cp -rf /var/named/* /chroot/named/var/named
#+END_SRC

- set the premission on the new files
#+BEGIN_SRC sh
chown named:named -R /chroot/named
#+END_SRC

- create the need device files
#+BEGIN_SRC sh
mknod /chroot/named/dev/random c 1 8
mknod /chroot/named/dev/null c 1 3
#+END_SRC

- add the correct permissions to the newly created devices
#+BEGIN_SRC sh
chmod 666 /chroot/named/dev
#+END_SRC

- restart the named service
#+BEGIN_SRC sh
systemctl restart named
#+END_SRC

- confirm with the changes have taken with dig
#+BEGIN_SRC sh
dig @localhost mailprod.mydomain.com
#+END_SRC

- to confirm that it's running in the jail remove the zone files from /var/named

** Configuring DNS Keys (needs tidying up)
   
- install the rng-tools
#+BEGIN_SRC sh
yum install rng-tools
#+END_SRC
this will provide us with the rngd tool that creates random data for the key creation(saves having to create data with random mouse and key presses)

- creating the keys
#+BEGIN_SRC sh
rngd -r /dev/urandom -o /dev/random -b
dnssec-keygen -a RSASHA1 -b 2048 -n ZONE -f KSK mydomain.com
dnssec-keygen -a RSASHA1 -b 1024 -n ZONE mydomain.com
#+END_SRC

- create a signed zone file
#+BEGIN_SRC sh
cp /var/named/fwd.mydomain.com.db .
dnssec-signzone -o mydomain.com -S fwd.mydomain.com.db
#+END_SRC
this will create a signed file fwd.mydoman.com.db.signed

** Configuring DANE, TLSA records
DANE - DNS-based Authentication of Named Entities   

TLSA record are used to hold the CA data
  - record has a basic syntax of:
  #+BEGIN_EXAMPLE
  certificate_usage selector matching_type content
  #+END_EXAMPLE
  
- certificate_usage filed is a single digit ranging from 0 - 3:
  - 0 - the record specifies an authorized and public CA. It offers no additional security so is not recommended. 
  - 1 - the record specifies a trusted cert or public key. It offers no additional security so is not recommended. 
  - 2 - the record specifies a non-public CA cert or its public key. Typically used when acting as your own CA. Often called a trust anchor assertion, this usage type does offer additional security.
  - 3 - the record specifies a server cert issued by the BIND administrator. This usage often called a domain-issued crtificate and allows the bypass of a third-party CA. This usage type does offer additional security.

- selector field is either 0 or 1:
  - 0 - indicates that the record is a digital cert
  - 1 - indicates that the record is a public key
    
- matching_type field is 0 - 2:
  - 0 - indicates that the content of the record is not hashed
  - 1 - indicates a SHA-256 hash
  - 2 - indicates a SHA-512 hash
the same hash should be used that the certs digital signature uses

* Lecture
* Tutorial
** Configuring BIND9 DNS - Linux Academy
LabGuide: [[file://home/crito/Documents/Linux/Labs/configuring-bind9.pdf][Configuring BIND9 DNS]]

- Server Install and Setup
  - first install apache2
    #+BEGIN_SRC sh
    apt-get install apache2
    #+END_SRC
    - this is just used to create a valid html page
  - test it's running
    #+BEGIN_SRC sh
    telnet 80
    helo
    #+END_SRC
  - create a file in /var/www
    - test.html
    #+BEGIN_EXAMPLE
    <html>
    <body>
      Test Page
    </body>
    </html>
    #+END_EXAMPLE
  - bind hostname to ip addr(local)
    - /etc/hosts
    #+BEGIN_EXAMPLE
    10.0.0.100		alickmitchell1.mylabserver.com
    #+END_EXAMPLE
  - install bind9
    #+BEGIN_SRC sh
    apt-get install bind9 bind9utils
    #+END_SRC
  - edit /etc/bind/named.conf.OPTIONS 
    #+BEGIN_EXAMPLE
    FORWARDERS {
    	10.0.0.2;
    	8.8.8.8;
    };
    #+END_EXAMPLE
  - edit /etc/bind/named.conf.local
    - adding zone information
    #+BEGIN_EXAMPLE
    zone "mylabserver.com" {
    	type master;
    	file "/etc/bind/zones/db.mylabserver.com";
    {;
    zone "0.0.10.in-addr.arpa"{
    	type master;
	file "/etc/bind/zones/db.10";
    };
    #+END_EXAMPLE
  - create a directory called /etc/bind/zones
  - copy db.local zones/db.mylabserver.com
  - edit db.mylabserver.com binding localhost to the zone we have created
  - copy db.127 zones/db.10 - this is for the reverse lookup
  - edit /edit/resolv.conf
    #+BEGIN_EXAMPLE
    nameserver	10.0.0.100
    nameserver	10.0.0.2
    search	mylabserver.com
    domain	mylabserver.com
    #+END_EXAMPLE
  - restart the bind service
    #+BEGIN_SRC sh
    service bind9 restart
    #+END_SRC
  - confirm that the dns server is resolving ip
    #+BEGIN_SRC sh
    tail -f /var/log/syslog
    #+END_SRC
  - test with nslookup check forward and reverse zone
    #+BEGIN_SRC sh
    nslookup mylabserver.com
    nslookup 10.0.0.100
    #+END_SRC
  
- Configure the client
  - ping bind server to check that they see each other
  - edit /etc/resolv.conf
    #+BEGIN_EXAMPLE
    nameserver	10.0.0.100
    nameserver	10.0.0.2
    search	mylabserver.com
    domain	mylabserver.com
    #+END_EXAMPLE
  - test pinging mylabserver.com
  - install lynx to test connection to webpage
    #+BEGIN_SRC sh
    apt-get install lynx
    lynx http://www.mylabserver.com/test.html
    #+END_SRC
  
* Books
[[file://home/crito/Documents/SysAdmin/DNS/Pro_DNS_and_BIND_10.pdf][Pro DNS and BIND 10]]
[[file://home/crito/Documents/SysAdmin/DNS/dns_and_bind-oreilly_5e.pdf][DNS and BIND - O'Reilly 5e]]

* Links
[[http://www.unixwiz.net/techtips/bind9-chroot.html][Building and Configuring BIND 9 in a chroot jail]]
