#+TAGS: arch_distro arch_linux manjaro


* Arch
HomePage: https://www.archlinux.org/

* Description
* Usage
** System Maintenance
*** Check for errors
- Failed systemd services
#+BEGIN_SRC sh
systemctl --failed
#+END_SRC
This will produce a list of services that are currently in a failed state

- Logfiles
- A quick examination of your log files in /var/log to see if there appear to be any errors or anomalies.
- Doing this regularly will also develop the "normal" overview of the system, so that errors are more easily spotted.
- Also check the systemd journal for any high priority errors
#+BEGIN_SRC sh
journalctl -p 3 -xb
#+END_SRC

*** Backup
- Makesure a list of all install pkgs is kept incase of full system rebuild
#+BEGIN_SRC sh
pacman -Qqen > pkglist.txt
#+END_SRC

- To install pkgs from the list use:
#+BEGIN_SRC sh
pacman -S - < pkglist.txt
#+END_SRC

- Makesure all AUR pkgs have been removed from the list with:
#+BEGIN_SRC sh
pacman -S $(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))
#+END_SRC

- Backup the LUKS header, if destoryed not able to access data on disk. As much of a dilemma as forgetting the passphrase or damaging the key-file used to unlock the partition.
#+BEGIN_SRC sh
cryptsetup luksHeaderBackup /dev/<device> --header-backup-file /mnt/<backup>/<file>.img
#+END_SRC

*** Upgrading the system 
- Avoid partial upgrades 
#+BEGIN_SRC sh
pacman -Sy
#+END_SRC

always use
#+BEGIN_SRC sh
pacman -Syu
#+END_SRC

- Always read [[https://www.archlinux.org/news/][Arch News]] just in case certain pkgs are casuing issues or have been dropped
- Deal with any .pacnew or .pacsave files created
- Clean up pkgs
  - check for oprhanded pkgs with [[file://home/crito/org/tech/cmds/lostfiles.org][lostfiles]]

*** Clean the filesystem
- Disk Usage
  - ncdu - nice overview of where disk is being spent
  
- Package Caching
  - remove unwanted .pkg files from /var/cache/pacman/pkg/

- Old Configuration
  - remove old config files as they remove cofusion in the future and possible corruption.
  - directories to check:
    - ~/.config - where apps store their configuration
    - ~/.cache - cache of some programs may grow in size
    - ~/.local/share - old files may be lying there

- Removal of duplicate files
  - [[https://tuxdiary.com/2015/04/13/rmlint/][rmlint]] can be run in the home dir to remove any cruft

- Remove Broken Links
The system can be checked for broken links with:
#+BEGIN_SRC sh
find -xtype l -print
#+END_SRC

** Networking
*** resolv.conf is recreated on boot
- make /etc/resolv.conf immutable
  - chattr +i /etc/resolv.conf

** PGP Keys
write up on how to resolve a corrupt keyring
** Fonts
Wiki: [[https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols][Arch-Fonts]]
*** Setting fonts for local user
- files need to be added to .local/share/fonts
** Hybrid Graphics
file://home/crito/org/tech/linux_concepts/hybrid_graphics.org

** Setting keyboard
- from the terminal
#+BEGIN_SRC sh
setxkbmap gb
#+END_SRC

** Setting default applications
*** mimeapps.list
/.config/mimeapps.list
#+BEGIN_SRC sh
[Default Applications]
x-scheme-handler/http=chromium.desktop
x-scheme-handler/https=chromium.desktop
x-scheme-handler/ftp=userapp-chromium.desktop
x-scheme-handler/chrome=userapp-chromium.desktop
text/html=chromium.desktop
application/x-extension-htm=userapp-chromium.desktop
application/x-extension-html=userapp-chromium.desktop
application/x-extension-shtml=userapp-chromium.desktop
application/xhtml+xml=userapp-chromium.desktop
application/x-extension-xhtml=userapp-chromium.desktop
application/x-extension-xht=userapp-chromium.desktop
image/jpeg=viewnior.desktop;gpicview.desktop;
image/png=viewnior.desktop;gpicview.desktop;
text/plain=mousepad.desktop
x-scheme-handler/mailto=userapp-mutt.desktop
message/rfc822=userapp-mutt.desktop
application/pdf=epdfview.desktop
application/x-bittorrent=transmission-gtk.desktop
x-scheme-handler/about=chromium.desktop
x-scheme-handler/unknown=chromium.desktop

[Added Associations]
x-scheme-handler/http=userapp-chromium.desktop;
x-scheme-handler/https=userapp-chromium.desktop;
x-scheme-handler/ftp=userapp-chromium.desktop;
x-scheme-handler/chrome=userapp-chromium.desktop;
text/html=userapp-chromium.desktop;
application/x-extension-htm=userapp-chromium.desktop;
application/x-extension-html=userapp-chromium.desktop;
application/x-extension-shtml=userapp-chromium.desktop;
application/xhtml+xml=userapp-chromium.desktop;
application/x-extension-xhtml=userapp-chromium.desktop;
application/x-extension-xht=userapp-chromium.desktop;
image/jpeg=viewnior.desktop;gpicview.desktop;
image/png=viewnior.desktop;gpicview.desktop;
text/plain=mousepad.desktop;
message/rfc822=userapp-mutt.desktop;
application/pdf=epdfview.desktop;
application/x-bittorrent=transmission-gtk.desktop;

#+END_SRC

*** xdg-settings
[[file://home/crito/org/tech/cmds/xdg-settings.org][xdg-settings]]

** Reinstall python
- update the system
#+BEGIN_SRC sh
pacman -Syu
#+END_SRC

- download the python packages into cache
#+BEGIN_SRC sh
pacman -Sw python python2
#+END_SRC

- close any running applications
  
- exit your WM or DE
  
- log into a tty and stop any none essential services
  
- remove the python
#+BEGIN_SRC sh
pacman -Rddn python python2
#+END_SRC

- install the python packages
#+BEGIN_SRC sh
pacman -S --asdeps python python2
#+END_SRC

* Package Management
** Files
/etc/pacman.conf         - this is the pacman configuration
/etc/pacman.d/mirrorlist - this file holds the repos that pacman will query
/var/log/pacman.log      - this log shows all package transactions

** Cmds
*** ABS(Arch Build System)
Arch: [[https://wiki.archlinux.org/index.php/Arch_Build_System][archlinux.org/Arch_Build_System]]
*** Repos
The repos are edited in /etc/pacman.conf

*** pacman
Arch: [[https://wiki.archlinux.org/index.php/Pacman][archlinux.org/pacman]]
Manjaro: https://wiki.manjaro.org/index.php/Pacman
- list installed pkgs
#+BEGIN_SRC sh
pacman -Q > pkg_list.txt
#+END_SRC

- update system
#+BEGIN_SRC sh
pacman -Syu
#+END_SRC
y - refrech database
u - update

- synchronise with the repositories
#+BEGIN_SRC sh
pacman -Syy
#+END_SRC
yy - force a refresh of database even if up to date

- update and sysnchronise with the repositories
#+BEGIN_SRC sh
pacman -Syyu
#+END_SRC

- delete orphaned pkgs
#+BEGIN_SRC sh
pacman -Rns $(pacman -Qtdq)
#+END_SRC

- Similar to autoremove in debian
#+BEGIN_SRC sh
pacman -R $(pacman -Qtdq)
#+END_SRC

- Search for a package
#+BEGIN_SRC sh
pacman -Ss vim
#+END_SRC
s - search

- Clean out the cache of downloads that have already been installed
#+BEGIN_SRC sh
pacman -Sc
#+END_SRC

- Completely clean out the cache
#+BEGIN_SRC sh
pacman -Scc
#+END_SRC

**** Holding a package from upgrading
/etc/pacman.conf
#+BEGIN_SRC sh
IgnorePkg=chromium
IgnoreGroup=gnome
#+END_SRC
**** Searching System
- search system for installed packages
#+BEGIN_SRC sh
pacman -Qs vim
#+END_SRC

- search system for installed packages with more information
#+BEGIN_SRC sh
pacman -Qi vim
#+END_SRC

- even more information with
#+BEGIN_SRC sh
pacman -Qii vim
#+END_SRC

- list all installed packages
#+BEGIN_SRC sh
pacman -Q
#+END_SRC

- list all installed packages and all associated files of package
#+BEGIN_SRC sh
pacman -Ql
#+END_SRC

- list all orphans
#+BEGIN_SRC sh
pacman -Qdt
#+END_SRC
d - dependencies
t - unrequired

**** pacman-mirrors
- change the repository branch
#+BEGIN_SRC sh
pacman-mirrors --branch testing
#+END_SRC
- stable
- testing
- unstable

**** pactree
this cmd provides the dependencies for a given package
- show an ascii tree
#+BEGIN_SRC sh
pacmantree -a zsh
#+END_SRC

- show a colour tree
#+BEGIN_SRC sh
pacmantree -c zsh
#+END_SRC

- show each dep on its own line
#+BEGIN_SRC sh
pacmantree -l zsh
#+END_SRC
this is more useful for scripts that need to pull data

- show packages that are dependent on a specific package
#+BEGIN_SRC sh
pacmantree -r glibc
#+END_SRC

*** yaourt
**** Diagnosis
- Search for pkg
#+BEGIN_SRC sh
yaourt -Ss python
#+END_SRC

- Provide yaourt Stats
#+BEGIN_SRC sh
yaourt --stats
#+END_SRC

- View all installed software
#+BEGIN_SRC sh
yaourt -Q
#+END_SRC

--date - will output list in chronological order
-t - this will output packages that have no dependencies

**** Operations
- Install pkg
#+BEGIN_SRC sh
yaourt -S python3.5
#+END_SRC

- Remove pkg
#+BEGIN_SRC sh
yaourt -Rsn python3.5
#+END_SRC

- upgrade system
#+BEGIN_SRC sh
yaourt -Syu
#+END_SRC

- Update repos
#+BEGIN_SRC sh
yaourt -Sy
#+END_SRC

- Build from source
#+BEGIN_SRC sh
yaourt -Sb
#+END_SRC

- Backup Database
#+BEGIN_SRC sh
yaourt -B
#+END_SRC

*** pacli
This tool is a tui for both pacman and yaourt

*** arch-audit
This is used to check installed packages for any CVEs

#+BEGIN_SRC sh
arch-audit
#+END_SRC
* Lectures
* Tutorial
* Articles
* Books
* Links


* Manjaro
* Description
* Usage
** Mirror List Error
- this will update the mirror list /etc/pacman.d/mirrorlist
#+BEGIN_SRC sh
sudo pacman-mirrors --fasttrack && sudo pacman -Syyu
#+END_SRC
this will create the file with the fastest mirrors at the top

* Lecture
* Tutorial
* Books
* Links
