#+TAGS: linux arch


* Arch								 :linux:arch:
* Description
* Usage
** System Maintenance
*** Check for errors
- Failed systemd services
#+BEGIN_SRC sh
systemctl --failed
#+END_SRC
This will produce a list of services that are currently in a failed state

- Logfiles
- A quick examination of your log files in /var/log to see if there appear to be any errors or anomalies.
- Doing this regularly will also develop the "normal" overview of the system, so that errors are more easily spotted.
- Also check the systemd journal for any high priority errors
#+BEGIN_SRC sh
journalctl -p 3 -xb
#+END_SRC

*** Backup
- Makesure a list of all install pkgs is kept incase of full system rebuild
#+BEGIN_SRC sh
pacman -Qqen > pkglist.txt
#+END_SRC

- To install pkgs from the list use:
#+BEGIN_SRC sh
pacman -S - < pkglist.txt
#+END_SRC

- Makesure all AUR pkgs have been removed from the list with:
#+BEGIN_SRC sh
pacman -S $(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))
#+END_SRC

- Backup the LUKS header, if destoryed not able to access data on disk. As much of a dilemma as forgetting the passphrase or damaging the key-file used to unlock the partition.
#+BEGIN_SRC sh
cryptsetup luksHeaderBackup /dev/<device> --header-backup-file /mnt/<backup>/<file>.img
#+END_SRC

*** Upgrading the system 
- Avoid partial upgrades 
#+BEGIN_SRC sh
pacman -Sy
#+END_SRC

always use
#+BEGIN_SRC sh
pacman -Syu
#+END_SRC

- Always read [[https://www.archlinux.org/news/][Arch News]] just in case certain pkgs are casuing issues or have been dropped
- Deal with any .pacnew or .pacsave files created
- Clean up pkgs
  - check for oprhanded pkgs with [[file://home/crito/org/tech/cmds/lostfiles.org][lostfiles]]

*** Clean the filesystem
- Disk Usage
  - ncdu - nice overview of where disk is being spent
  
- Package Caching
  - remove unwanted .pkg files from /var/cache/pacman/pkg/

- Old Configuration
  - remove old config files as they remove cofusion in the future and possible corruption.
  - directories to check:
    - ~/.config - where apps store their configuration
    - ~/.cache - cache of some programs may grow in size
    - ~/.local/share - old files may be lying there

- Removal of duplicate files
  - [[https://tuxdiary.com/2015/04/13/rmlint/][rmlint]] can be run in the home dir to remove any cruft

- Remove Broken Links
The system can be checked for broken links with:
#+BEGIN_SRC sh
find -xtype l -print
#+END_SRC

** Package Management
[[file:~/org/tech/system/pkg_mgmt.org][Package Management]]

** PGP Keys
write up on how to resolve a corrupt keyring
** Fonts 							       :font:
Wiki: [[https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols][Arch-Fonts]]
*** Setting fonts for local user
- files need to be added to .local/share/fonts
* Lectures
* Tutorial
* Articles
* Books
* Links
