#+TAGS: dns_records


* DNS Record Types
- NS - NS record maps a domain to a list of DNS servers authoritative for that domain.

- SOA - provides authoritative information about the domain.

The recieved informaiton:

mail addr - specifies the email address of the admin

serial - sort of revision numbering system. The standard convention is
to use "YYYYMMYYNN"

refresh - specifies (in seconds), when the secondary DNS Will poll the
primary to see if the serial number has been increased . If increased,
secondary will make a new request to copy the new zone file.

retry - specifies the interval to reconnect with the Primary DNS.

expire -  specifies the time that the secondary DNS will keep the cached
zone file as valid.

minimum - specifies the time that the secondary DNS should cache the
zone file.

- MX - Mail Exchange record, maps a domain name to a list of message transfer agents for the domain.

- A - This is a 32bit ipv4 address most commonly used to map hostnames to ip addresses. It is also used for DNSBL.

- AAAA - This returns a 128bit ipv6 address most commonly used to map hostnames to ip addresses.

- PTR - Pointer record, pointer to a canonical name. Unlike CNAME, DNS processing stops and just returns the name. The most common use is for implementing reverse DNS lookups

- AFSDB - This record is commonly used by AFS clients to contact AFS cells outside their local domain.

- APL - Specify list of address ranges. Experimental

- CAA - DNS Certification Authority Authorization, constraining acceptable CAs for a host/domain.

- CDNSKEY - Child copy of DNSKEY record, for transfer to parent.

- CDS - Child copy of DS record for transfer to parent.

- CERT - Certificate record stores PKIX, SPKI, PGP, etc

- CNAME - Canonical name record, alias of one name to another the DNS lookup will continue by retrying the lookup with the new name.

- DHCID - DHCP identifier, used in conjunction with the FQDN option to DHCP.

- DLV - DNSSEC Lookaside Validation record, for publishing DNSSEC trust anchors outside of the DNS delegation chain.

- DNAME - Delegation Name, alias for a name and all its subnames. Unlike CNAME which is an alias for the exact name. Like a CNAME record, the DNS lookup will continue by retrying the lookup with the new name.

- DNSKEY - DNS Key record, the key record used in DNSSEC. Uses the same format as the KEY record.

- DS - Delegation Signer, this record is used to identify the DNSSEC signing key of a delegated zone.

- HIP - Host Identify Protocol, method of seperating the end-point identifier and locator roles of ip addresses.

- IPSECKEY - IPsec Key, key record that can be used with IPsec.

Key -

- TXT - Originally for arbitrary human-readable text in a DNS record. Since the early 90s, this record more often carries machine-readable data

- URI - Uniform Resource Identifier, can be used for publishing mappings from hostnames to URIs.

* Lecture
* Tutorial
* Books
* Links
https://en.wikipedia.org/wiki/List\_of\_DNS\_record\_types

*To be continued*

Links:

