#+TAGS: glossary


* AMI  - Amazon Machine Image
AWS:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
* API  - Application Programming Interface
Wiki: https://en.wikipedia.org/wiki/Application_programming_interface
* APCI - Advanced Configuration and Power Interface
Arch: https://wiki.archlinux.org/index.php/ACPI_modules
* ASLR - Address Space Layout Randomization
Wiki: https://en.wikipedia.org/wiki/Address_space_layout_randomization
* BGP  - Border Gate Protocol
wiki: https://en.wikipedia.org/wiki/Border_Gateway_Protocol
* CIDR - Classless Inter-Domain Routing
Wiki: https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing
* CNI  - Container Network Interface
flannel 
* CRUD - Create Read Update Delete
* CVE  - Common Vulnerabilities and Exposures
HomePage: https://cve.mitre.org/
* DCCP - Datagram Congestion Control Protocol
Wiki - https://en.wikipedia.org/wiki/Datagram_Congestion_Control_Protocol
* DDC  - Display Data Channel
Wiki: https://en.wikipedia.org/wiki/Display_Data_Channel
* DMA  - Direct Memory Access
* DRM  - Direct Rendering Manager
HomePage: https://dri.freedesktop.org/wiki/DRM/
* DRY  - Don't Repeat Yourself
* FDT  - Flattened Device Tree
* FD   - Fast Data Project
Homepage: https://fd.io/
* GIMP - GNU Image Manipulation Program
HomePage: https://www.gnome.org/
* GNOME - GNU Network Object Model Environment
HomePage: https://www.gnome.org/
* GSSAPI - Generic Security Services Application Programming Interface
Wiki: https://en.wikipedia.org/wiki/Generic_Security_Services_Application_Program_Interface
* ISDN - Integrated Services Digital Network
Wiki: https://en.wikipedia.org/wiki/Integrated_Services_Digital_Network
* iSCSI - Internet Small Computer Systems Interface
wiki: https://en.wikipedia.org/wiki/ISCSI
* IIO  - Industrial I/O Subsystem
https://wiki.analog.com/software/linux/docs/iio/iio
* KDC  - Key Distribution Centre
* LDAP - Lightweight Directory Access Protocol
- setting the daemon to i
* LDPD - Label Distributed Protocol Daemon
ManPage: https://man.openbsd.org/ldpd
* LDA  - Local Delivery Agent
[[file://home/crito/org/tech/mail/procmail.org][Procmail]]
maildrop

* LMDB - Lightnig Memory-Mapped Database
Wiki: https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database
HomePage: http://www.lmdb.tech/doc/
* LUN  - Logical Unit Number
* MMIO - Memory Mapped I/O
* MPLS - Multiprotocol Label Switching
Wiki: https://en.wikipedia.org/wiki/Multiprotocol_Label_Switching
* MTU  - Maximum Transmission Unit
Wiki: https://en.wikipedia.org/wiki/Maximum_transmission_unit
* NVN  - National Vulnerability Database
https://nvd.nist.gov/
* NIS  - Network Information Service
* NNTP - News Network Transport Protocol
Wiki: https://en.wikipedia.org/wiki/Network_News_Transfer_Protocol
* NSS  - Name Service Switch
Wiki: https://en.wikipedia.org/wiki/Name_Service_Switch
* NTP  - Network Time Protocol
HomePage: http://www.ntp.org/
* NUMA - Non Uniform Memory Access 
Wiki: https://en.wikipedia.org/wiki/Non-uniform_memory_access
Non-uniform memory access (NUMA) is a computer memory design used in multiprocessing, where the memory access time depends on the memory location relative to the processor. Under NUMA, a processor can access its own local memory faster than non-local memory (memory local to another processor or memory shared between processors). The benefits of NUMA are limited to particular workloads, notably on servers where the data is often associated strongly with certain tasks or users.
* ONAP - Open Network Automation Platform
Homepage: https://www.onap.org/
* OPNFV - Open Platform Network Function Virtulization
Homepage: https://www.opnfv.org/
* OSPF - Open Shortest Path First protocol
wiki: https://en.wikipedia.org/wiki/Open_Shortest_Path_First
* PAM  - Pluggable Authenication Module
Wiki: https://en.wikipedia.org/wiki/Pluggable_authentication_module
Red hat: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/managing_smart_cards/pluggable_authentication_modules

* PNDA - Platform for Network Data Analysis
Homepage: http://pnda.io/
* RAC  - Real Application Clustering (oracle)
* RHEL - Red Hat Enterprise Linux
* RESTful API - Repressentational State Transfer Application Programming Interface
Wiki: https://en.wikipedia.org/wiki/Representational_state_transfer
* SSSD - System Security Services Daemon
Fedora - https://fedoraproject.org/wiki/Features/SSSD

* SAML - Security Assertion Markup Language
Wiki: https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language
* SASL - Simple Authentication and Security Layer
Wiki: https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer

* SCM  - Source Code Management
refers to tools such as git and subversion
* SDK  - Software Development Kit
Wiki: https://en.wikipedia.org/wiki/Software_development_kit
* SDLC - Software Development Life Cycle
* SMB  - Server Message Block
* SNAS - Streaming Network Analytics System
Homepage: http://www.snas.io/
* SNI  - Server Name Indication
Server Name Indication (SNI) is an extension to the TLS computer networking protocol[1] by which a client indicates which hostname it is attempting to connect to at the start of the handshaking process. This allows a server to present multiple certificates on the same IP address and TCP port number and hence allows multiple secure (HTTPS) websites (or any other Service over TLS) to be served by the same IP address without requiring all those sites to use the same certificate. It is the conceptual equivalent to HTTP/1.1 name-based virtual hosting, but for HTTPS. The desired hostname is not encrypted,[2] so an eavesdropper can see which site is being requested.
* SPI  - Serial Peripheral Interface bus
* SSO  - Single Sign On
* SSSD - System Security Services Daemon
RHEL: [[https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/5.7_Release_Notes/sssd.html][redhat.com/5/sssd]]
* SLES - SUSE Linux Enterprise Server
* STS  - Security Token Service
Doc: https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html

The AWS Security Token Service (STS) is a web service that enables you to request temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users or for users that you authenticate (federated users)

* TLS  - Transport Layer Security
Wiki: https://en.wikipedia.org/wiki/Transport_Layer_Security
* TWM  - Tab Window Manager
Wiki: https://en.wikipedia.org/wiki/Twm
* UAT  - User Acceptence Testing
* UUCP - Unix-to-Unix Copy
Wiki: https://en.wikipedia.org/wiki/UUCP
* UCE  - Unsolicited Commercial Email
* VTL  - Virtual Tape Library
