#+TAGS: glossary


* A2DP - Advanced Audio Distribution Profile
Wiki: https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Advanced_Audio_Distribution_Profile_(A2DP)

* ACPI - Advanced Configuration and Power Interface
HomePage: http://www.acpi.info/
* AMI  - Amazon Machine Image
AWS:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
* API  - Application Programming Interface
Wiki: https://en.wikipedia.org/wiki/Application_programming_interface
* APCI - Advanced Configuration and Power Interface
Arch: https://wiki.archlinux.org/index.php/ACPI_modules
* ASG  - Auto Scaling Group (AWS)
Docs: https://aws.amazon.com/autoscaling/
* ASLR - Address Space Layout Randomization
Wiki: https://en.wikipedia.org/wiki/Address_space_layout_randomization
* BGP  - Border Gate Protocol
wiki: https://en.wikipedia.org/wiki/Border_Gateway_Protocol
* BOFH - Bastard Operator From Hell
* CAM  - Content Addressable Memory
Wiki: https://en.wikipedia.org/wiki/Content-addressable_memory
* CERT - Computer Emergency Response Team
Coordination Center or Cert-CC located at Carnegie Mellon University
* CIDR - Classless Inter-Domain Routing
Wiki: https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing
* CNI  - Container Network Interface
flannel 
* CMS  - Conversational Monitor System
Wiki: https://en.wikipedia.org/wiki/Conversational_Monitor_System
* COA  - Certificate of Authenticity
Microsoft: https://www.msembedded.biz/en/licensing/license-sticker/
* CORS - Cross Origin Resource Sharing
Wiki: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
* CP/M - Control Program for Microcomputers
DigitalReseach: http://www.digitalresearch.biz/CPM.HTM
* CRUD - Create Read Update Delete
* CTSS - Compatible Time Sharing System
Wiki: https://en.wikipedia.org/wiki/Compatible_Time-Sharing_System
* CVE  - Common Vulnerabilities and Exposures
HomePage: https://cve.mitre.org/
* DCCP - Datagram Congestion Control Protocol
Wiki - https://en.wikipedia.org/wiki/Datagram_Congestion_Control_Protocol
* DDC  - Display Data Channel
Wiki: https://en.wikipedia.org/wiki/Display_Data_Channel
* DMA  - Direct Memory Access
* DRM  - Direct Rendering Manager
HomePage: https://dri.freedesktop.org/wiki/DRM/
* DRY  - Don't Repeat Yourself
* DSL  - Domain Specific Language
Wiki: https://en.wikipedia.org/wiki/Domain-specific_language
* EBS  - Elastic Block Storage (AWS)
Docs: https://aws.amazon.com/ebs/
* EC3  - Europol's European Cybercrime Centre
HomePage: https://www.europol.europa.eu/about-europol/european-cybercrime-centre-ec3
* EFS  - Elastic File System (AWS)
Docs: https://aws.amazon.com/efs/
* EOL  - End Of Life (Linux)
Debian - https://wiki.debian.org/DebianReleases
Ubuntu - https://www.ubuntu.com/info/release-end-of-life
RHEL   - https://access.redhat.com/support/policy/updates/errata/
CentOS - https://endoflife.software/operating-systems/linux/centos

* ETL  - Extract Transform Load
Wiki: https://en.wikipedia.org/wiki/Extract,_transform,_load
* FDT  - Flattened Device Tree
* FD   - Fast Data Project
Homepage: https://fd.io/
* FPU  - Floating Point Unit
Wiki: https://en.wikipedia.org/wiki/Floating-point_unit
* FQDN - Fully Qualified Domain Name
Indiana Uni: https://kb.iu.edu/d/aiuv
* GA   - General Availability (Software Cycle)
Wiki: https://en.wikipedia.org/wiki/Software_release_life_cycle
* GIMP - GNU Image Manipulation Program
HomePage: https://www.gnome.org/
* GNOME - GNU Network Object Model Environment
HomePage: https://www.gnome.org/
* GPT  - GUID Partition Table
Wiki: https://en.wikipedia.org/wiki/GUID_Partition_Table
* GSSAPI - Generic Security Services Application Programming Interface
Wiki: https://en.wikipedia.org/wiki/Generic_Security_Services_Application_Program_Interface
* HPC  - High Performance Computing
Wiki: https://en.wikipedia.org/wiki/Supercomputer
* HSTS - HTTP Strict Transport Security
Wiki: https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
* IAM  - Identity and Access Management (AWS)
Docs: https://aws.amazon.com/iam/
* IMAP - Internet Message Access Protocol
Book: [[file://home/crito/Documents/SysAdmin/Mail/The_Book_of_IMAP.pdf][The Book of IMAP]]

* ISA  - Instruction Set Architecture
Wiki: https://en.wikipedia.org/wiki/Instruction_set_architecture
* ISDN - Integrated Services Digital Network
Wiki: https://en.wikipedia.org/wiki/Integrated_Services_Digital_Network
* iSCSI - Internet Small Computer Systems Interface
wiki: https://en.wikipedia.org/wiki/ISCSI
* IIO  - Industrial I/O Subsystem
https://wiki.analog.com/software/linux/docs/iio/iio
* IPC  - Inter-Process Communication
Book: [[file://home/crito/Documents/Computer_Science/Operating_Sys/Operating_Systems-Design_and_Implementations.pdf][Operating Systems - Design and Implementation - Tanenbaum - Chp 2]]

* JSON - JavaScript Object Notation
Wiki: https://en.wikipedia.org/wiki/JSON

* JWT  - JSON Web Token
Wiki: https://en.wikipedia.org/wiki/JSON_Web_Token
* KDC  - Key Distribution Centre
* LDAP - Lightweight Directory Access Protocol
- setting the daemon to i
* LDIP - LDAP Interchange Format
It is used to create objects within the OpenLDAP directory. These values are placed into a file and can be loaded into the directory with the slapadd command.
* LDPD - Label Distributed Protocol Daemon
ManPage: https://man.openbsd.org/ldpd
* LDA  - Local Delivery Agent
[[file://home/crito/org/tech/mail/procmail.org][Procmail]]
maildrop

* LILO - Linux Loader
wiki: https://en.wikipedia.org/wiki/LILO_%28boot_loader%29
* LKM  - Loadable Kernel Module
Wiki: https://en.wikipedia.org/wiki/Loadable_kernel_module
tlpd: http://tldp.org/HOWTO/Module-HOWTO/x73.html
* LMDB - Lightnig Memory-Mapped Database
Wiki: https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database
HomePage: http://www.lmdb.tech/doc/
* LSB  - Linux Standard Base
Wiki: https://en.wikipedia.org/wiki/Linux_Standard_Base
* LUN  - Logical Unit Number
* MMIO - Memory Mapped I/O
* MPLS - Multiprotocol Label Switching
Wiki: https://en.wikipedia.org/wiki/Multiprotocol_Label_Switching
* MTU  - Maximum Transmission Unit
Wiki: https://en.wikipedia.org/wiki/Maximum_transmission_unit
* MULTICS - MULTiplexed Information and Computing Service
Wiki: https://en.wikipedia.org/wiki/Multics
* MVC  - Model View Controller
Wiki: https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller
* NACL - Network Access Control Lists
AWS_Docs: https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ACLs.html
* NAT  - Network Address Translation
Wiki: https://en.wikipedia.org/wiki/Network_address_translation
* NIDS - Network Intrusion Detection System
Wiki: https://en.wikipedia.org/wiki/Intrusion_detection_system
* NIS  - Network Information Service
* NIST - National Institure of Standards and Technology
HomePage: https://www.nist.gov/
* NNTP - News Network Transport Protocol
Wiki: https://en.wikipedia.org/wiki/Network_News_Transfer_Protocol
* NSS  - Name Service Switch
Wiki: https://en.wikipedia.org/wiki/Name_Service_Switch
* NTP  - Network Time Protocol
HomePage: http://www.ntp.org/
* NUMA - Non Uniform Memory Access 
Wiki: https://en.wikipedia.org/wiki/Non-uniform_memory_access
Non-uniform memory access (NUMA) is a computer memory design used in multiprocessing, where the memory access time depends on the memory location relative to the processor. Under NUMA, a processor can access its own local memory faster than non-local memory (memory local to another processor or memory shared between processors). The benefits of NUMA are limited to particular workloads, notably on servers where the data is often associated strongly with certain tasks or users.
* NVN  - National Vulnerability Database
https://nvd.nist.gov/
* MMU  - Memmory Management Unit
Wiki: https://en.wikipedia.org/wiki/Memory_management_unit
* OCSP - Online Certifiacte Status Protocol
Wiki: https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol
* ONAP - Open Network Automation Platform
Homepage: https://www.onap.org/
* OPNFV - Open Platform Network Function Virtulization
Homepage: https://www.opnfv.org/
* OSPF - Open Shortest Path First protocol
wiki: https://en.wikipedia.org/wiki/Open_Shortest_Path_First
* PAM  - Pluggable Authenication Module
Wiki: https://en.wikipedia.org/wiki/Pluggable_authentication_module
Red hat: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/managing_smart_cards/pluggable_authentication_modules

* POP  - Post Office Protocol
Wiki: https://en.wikipedia.org/wiki/Post_Office_Protocol
* PNDA - Platform for Network Data Analysis
Homepage: http://pnda.io/
* RAC  - Real Application Clustering (oracle)
* RAT  - Remote Access Trojan
MalwarebytesLabs: https://blog.malwarebytes.com/threats/remote-access-trojan-rat/
* RESTful API - Repressentational State Transfer Application Programming Interface
Wiki: https://en.wikipedia.org/wiki/Representational_state_transfer
* RHEL - Red Hat Enterprise Linux
* RISC - Reduced Instruction Set Computer
Wiki: https://en.wikipedia.org/wiki/Reduced_instruction_set_computer
* RPO  - Recovery Point Objective
Acceptable amount of data lass measured in time
* RTO  - Recovery Time Objective
The time it takes after a disruption to restore operations back to its regular service level, as defined by the companies operational level agreeement.
* S3   - Simple Storage Service (AWS)
Docs: https://aws.amazon.com/s3/

* SMP  - Symetrical Multi-Processor
This is a type of kernel that is used for systems that have multi-core processors
* SAML - Security Assertion Markup Language
Wiki: https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language
* SASL - Simple Authentication and Security Layer
Wiki: https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer

* SCM  - Source Code Management
refers to tools such as git and subversion
* SDK  - Software Development Kit
Wiki: https://en.wikipedia.org/wiki/Software_development_kit
* SDLC - Software Development Life Cycle
* SLES - SUSE Linux Enterprise Server
* SMB  - Server Message Block
* SNAS - Streaming Network Analytics System
Homepage: http://www.snas.io/
* SNI  - Server Name Indication
Server Name Indication (SNI) is an extension to the TLS computer networking protocol[1] by which a client indicates which hostname it is attempting to connect to at the start of the handshaking process. This allows a server to present multiple certificates on the same IP address and TCP port number and hence allows multiple secure (HTTPS) websites (or any other Service over TLS) to be served by the same IP address without requiring all those sites to use the same certificate. It is the conceptual equivalent to HTTP/1.1 name-based virtual hosting, but for HTTPS. The desired hostname is not encrypted,[2] so an eavesdropper can see which site is being requested.
* SOA  - Start of Authority (DNS record)
Wiki: https://en.wikipedia.org/wiki/SOA_record
* SPI  - Serial Peripheral Interface bus
* SPOOL - Simultaneous Peripheral Operation On Line  
* SRE  - Site Reliability Engineering/Engineer
Google: https://landing.google.com/sre/
* SSSD - System Security Services Daemon
Fedora - https://fedoraproject.org/wiki/Features/SSSD
RHEL: [[https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/5.7_Release_Notes/sssd.html][redhat.com/5/sssd]]
This provices authentication of user accounts for OpenLDAP
* SSO  - Single Sign On
* STS  - Security Token Service
Doc: https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html

The AWS Security Token Service (STS) is a web service that enables you to request temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users or for users that you authenticate (federated users)

* TLB  - Translation Lookaside Buffer
Wiki: https://en.wikipedia.org/wiki/Translation_lookaside_buffer
* TLS  - Transport Layer Security
Wiki: https://en.wikipedia.org/wiki/Transport_Layer_Security
* TWM  - Tab Window Manager
Wiki: https://en.wikipedia.org/wiki/Twm
* UAT  - User Acceptence Testing
* UCE  - Unsolicited Commercial Email
* UEFI - Unified Extensible Firmware Interface
HomePage: http://www.uefi.org/
Wiki: https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface
* US-CERT - United States - Computer Emergency Response Team
HomePage: https://www.us-cert.gov/
* UUCP - Unix-to-Unix Copy
Wiki: https://en.wikipedia.org/wiki/UUCP
* UUID - Universal Unique ID
Linux.com: https://www.linux.com/news/what-uuids-can-do-you
* VTL  - Virtual Tape Library
* XML  - Extensible Markup Language
Wiki: https://en.wikipedia.org/wiki/XML
