#+TAGS: ci cd java code build devops build_automation


* Gradle
HomePage: https://gradle.org/

* Description
Gradle combines good parts of both tools and builds on top of them with DSL and other improvements. It has Ant’s power and flexibility with Maven’s life-cycle and ease of use. The end result is a tool that was released in 2012 and gained a lot of attention in a short period of time. For example, Google adopted Gradle as the default build tool for the Android OS.

Gradle does not use XML. Instead, it had its own DSL based on Groovy (one of JVM languages). As a result, Gradle build scripts tend to be much shorter and clearer than those written for Ant or Maven. The amount of boilerplate code is much smaller with Gradle since its DSL is designed to solve a specific problem: move software through its life cycle, from compilation through static analysis and testing until packaging and deployment.

Initially, Gradle used Apache Ivy for its dependency management. Later own it moved to its own native dependency resolution engine.

Gradle effort can be summed as “convention is good and so is flexibility”.

* Usage
  
** Installation of Gradle CentOS7

- we will need Java JDK 7 or higher
#+BEGIN_SRC sh
yum install java-1.8.0-openjdk unzip
#+END_SRC  

- pull gradle
#+BEGIN_SRC sh
wget -O ~/gradle-4.7 https://services.gradle.org/distributions/gradle-4.7-bin.zip
#+END_SRC

- unzip gradle file
#+BEGIN_SRC sh
mkdir /opt/gradle
unzip -d /opt/gradle ~/gradle-4.7-bin.zip
#+END_SRC

- create /etc/profile.d/gradle.sh
#+BEGIN_EXAMPLE
export PATH=$PATH:/opt/gradle/gradle-4.7/bin
#+END_EXAMPLE

-set correct permissions on the gradle.sh file
#+BEGIN_SRC sh
chmod 755 /etc/profile.d/gradle.sh
#+END_SRC

- logout and back in for the $PATH variable to take effect
  
- confirm that gradle has sucessfully installed
#+BEGIN_SRC sh
gradle --version
#+END_SRC



** Installing the Gradle Wrapper (this is with a version of Gradle already installed)

- inside project directory run the gradle wrapper cmd
#+BEGIN_SRC sh
cd my-project
gradle wrapper
#+END_SRC

- this will create few files and directories
  - gradlew
  - gradlew.bat (windows)
  - gradle
    
- to build the project just run gradlew
#+BEGIN_SRC sh
./gradlew build
#+END_SRC
this will download the correct version of gradle and build the project

* Lecture
* Tutorial
* Books
* Links
