#+TAGS: virt cloud net devops


* Kubernetes                                          :virt:cloud:net:devops:
HomePage: [[https://kubernetes.io/][kubernetes.io]]
List of Materials: [[https://github.com/ramitsurana/awesome-kubernetes][github.com/awesome-kubernetes]]

* Cmds
- kubectl
- kubecfg

* Description
** Components
- Master - the managing machine, which oversees one or more minions.
- Minion - a slave that runs tasks as delegated by the user and Kubernetes master.
- Pod - an application (or part of an application) that runs on a minion. This is the basic unit of manipulation in Kubernetes.
- Replication Controller - ensures that the requested number of pods are running on minions at all times.
- Label - an arbitrary key/value pair that the Replication Controller uses for service discovery
- Kubecfg - the command line config tool
- Service - an endpoint that provides load balancing across a replicated group of pods

* Usage

- Kubernetes UI
https://<your_master_ip>/api/v1/proxy/namespaces/kube-system/services/kube-ui  

- Grafana
https://<your_master_ip>/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana

- Swagger
https://<your_master_ip>/swagger-ui/

* Lecture
* Tutorial
* Books
** [[file://home/crito/Documents/SysAdmin/Cloud/Getting_Started_with_Kubernetes.pdf][Getting Started with Kubernetes]]

* Links
