#+TAGS: dns


* DNS
* Description
This is a small exaple of how DNS is structured
         . root
         |
     ---------------
     |      |      |
    com    net    org
     |
 ---------
 |   |   |
cnn  |  microsoft
     |
  server1
     |
    ns <--------------- you
You request an address lookup from your name server, if it isn't already in the cache it will recursivley ask the name servers, starting with root until it eventually is given the ip.

Different DNS Sever Roles
- Primary (master) Nameserver
- Secondary (slave) Nameserver
- Cache only Nameserver
  
Recource Records
A     - name to IP Address
AAAA  - name to IPv6 Address
CNAME - Canonical Name; alias 
PTR   - Reverse DNS Resolution
NS    - Name Server; which name server is authoritative
SOA   - Start Of Authority; generic information about a domain
MX    - Mail Exchange tht is responsible for this domain
TXT   - Supplies additional data,such as data that is used by sender policy framework networks and related 
SRV   - Hosts that provide a specific service

* Public Servers
** Google
8.8.8.8
8.8.4.4
2001:4860:4860::8888
2001:4860:4860::8844

** OpenDNS
208.67.222.222
208.67.220.220
2620:0:ccc::2
2620:0:ccd::2

* Services
[[file://home/crito/org/tech/dns/bind.org][BIND]]
[[file://home/crito/org/tech/dns/nsd.org][NSD]]
file://home/crito/org/tech/dns/unbound.org
file://home/crito/org/tech/dns/maradns.org

* Authoritative Vs Non-authoritative Answer

If the answer for the query comes from a name server that contains the
complete zone file information for the domain the answer is said to be
authoritative.

If the server doesn't contain the complete zone file information for the
domain the answer is said to be non-authoritative. The name server
contains a cached file which has the results of all queries performed in
the past for which it has gotten authoritative response. When a DNS
query is given, it searches the cache file and returns the available
information.
#+TAGS:

* Lecture
* Tutorial
* Books
[[file://home/crito/Documents/SysAdmin/DNS/dns_and_bind-oreilly_5e.pdf][DNS and BIND - O'Reilly]]
[[file://home/crito/Documents/SysAdmin/DNS/DNS_and_BIND_on_IPv6.pdf][DNS and BIND on IPv6]]
[[file://home/crito/Documents/SysAdmin/DNS/DNS_HowTo_for_Linux.pdf][DNS HowTo for Linux]]
[[file://home/crito/Documents/SysAdmin/DNS/Pro_DNS_and_BIND_10.pdf][Pro DNS and BIND 10]]
* Links
[[http://www.linuxjournal.com/article/4597][linuxjournal.com - An Introduction to DNS and DNS tools]]
