#+TAGS: dns


* DNS                                                                   :dns:
* Description
* Usage
* Public Servers
** Google
8.8.8.8
8.8.4.4
2001:4860:4860::8888
2001:4860:4860::8844

** OpenDNS
208.67.222.222
208.67.220.220
2620:0:ccc::2
2620:0:ccd::2

* Services
[[file://home/crito/org/tech/dns/bind.org][BIND]]
[[file://home/crito/org/tech/dns/nsd.org][NSD]]
file://home/crito/org/tech/dns/maradns.org

* Authoritative Vs Non-authoritative Answer

If the answer for the query comes from a name server that contains the
complete zone file information for the domain the answer is said to be
authoritative.

If the server doesn't contain the complete zone file information for the
domain the answer is said to be non-authoritative. The name server
contains a cached file which has the results of all queries performed in
the past for which it has gotten authoritative response. When a DNS
query is given, it searches the cache file and returns the available
information.
#+TAGS:

* Lecture
* Tutorial
* Books
file://home/crito/Documents/SysAdmin/DNS/DNS_and_Bind_on_IPv6.pdf
* Links
[[http://www.linuxjournal.com/article/4597][linuxjournal.com - An Introduction to DNS and DNS tools]]
