#+TAGS: ldap active_directory


* LDAP
OpenLDAP: [[https://www.openldap.org/][openldap.org]]

* Files
/etc/openldap   - the main ldap configuration file
/etc/slapd.conf - this is the openldap server configuration file
/var/lib/ldap   - this is the default location for the ldap db

* Cmds
** Client Utils
- ldapadd     - Allows you to add entries to an LDaP directory, wither from a file, or fromm standard input. It is a symbolic link to ldapmodify -a
- ldacompare  - Allows you to compare given attribure with an LDAP directory entry
- ldapdelete  - Allows you to delete entries from an LDAP directory    
- ldapexop    - Allows you to perform extended LDAP operations
- ldapmodify  - Allows you to modify entries in an LDAP directory, wither from a file, or from standard input
- ldamodrdn   - Allows you to modify the RDN value of an LDAP directory entry
- ldappasswd  - Allows you to set or change the password for an LDAP user
- ldapsearch  - Allows you to search LDAP directory entries
- ldapurl     - Allows you to compose or decompose LDAP URLs
- ldapwhoami  - Allows you to perform a whoami operation on an LDAP server

** Server Utils
- slapacl     - Allows you to check the access to a list of attributes
- slapadd     - allows you to add entires from ann LDIF file to an LDAP directory
- slapauth    - Allows you to checka list of IDs for authentication and authorization permissions
- slapcat     - Allows you to pull entries from an LDAP directory in the default format and save them in an LDIF file
- slapdn      - Allows you to check a list of Distinguished Names (DNs) based on available schema syntax
- slapindex   - Allows you to re-index the slapd directory based on the current content. Run this utility whenever you change indexing options in the configuration file
- slappasswd  - Allows you to create an encrypted user password to be used with the ldapmodify utility, or in the slapd configuration file
- slapschema  - Allows you to check the compliance of a database with the corresponding schema
- slaptest    - Allows you to check the LDAP server configuration

* Server
** OpenLDAP - slapd
** 389 Directory Server
- possible to handle thousands of operations
- TLS
- SASL

*** Setup on RHEL/CENTOS
1. install the EPEL repo
#+BEGIN_SRC sh
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
rpm -ivh epel-release-7-9.noarch.rpm 
#+END_SRC

2. ensure that the host file is configured correctly
   
3. set appropriate /etc/sysctl.conf

* Overview
OpenLDAP is a distributed directory service. It stores information associated with users that can be used to authenticate them for login and provide other informatin about those users(home directories, roles within the organization, etc).

OpenLDAP is most commonly used in Linux, but can be compared to Active Directory on Windows as a service provided hierarchical based user information much the same as OpenLDAP.

LDAP uses the Sleepycat Berkley DB, 

String X.500 AttributeType
dn     - distinguished name
cn     - common name
l      - locality name
st     - state or province name
o      - organisation name
ou     - organisational unit name
c      - country name
street - street name
dc     - domain component
uid    - userid
mail   - email address

* Usage
** Install OpenLDAP on CentOS5 LPIC2 (this is Legacy)
OpenLDAP V2.3.x

- install the required pkgs
#+BEGIN_SRC sh
yum install openldap openldap-servers openldap-clients
#+END_SRC

- makesure that the database directory has been set in /etc/slapd.conf
#+BEGIN_EXAMPLE
directory	/var/lib/ldap
#+END_EXAMPLE

- set the correct domain settings
/etc/slapd.conf
#+BEGIN_EXAMPLE
database	bdb
suffix		"dc=mydomain,dc=com"
rootdn		"cn=admin,dc=mydomain,dc=com"
#+END_EXAMPLE
rootdn - this has the authority to query, change passwords, add objects

- add the rootdn password
/etc/slapd.conf
#+BEGIN_EXAMPLE
rootpw		p@$$w0rd
#+END_EXAMPLE
this would set the password in plain text(not recommended) 

- add logging
/etc/slapd.conf
#+BEGIN_EXAMPLE
loglevel	2048
#+END_EXAMPLE

- test the configuration
#+BEGIN_SRC sh
slaptest -u -v
#+END_SRC

- makesure that ldap owns the /var/lib/ldap directory
#+BEGIN_SRC sh
chown ldap:ldap -R /var/lib/ldap
#+END_SRC

- start and enable the service
#+BEGIN_SRC sh
service ldap start
chkconfig ldap on
#+END_SRC

*** Adding a hashed password
- created the hashed password
#+BEGIN_SRC sh
slappasswd
#+END_SRC
this will prompt you for the a password and will output a hash

- take the hash and replace the plaintext passwd in /etc/slapd.conf
#+BEGIN_EXAMPLE
rootpw		{SSHA}KdsV4isxGUWSVYyaUiCgD1KFsJPI9ldc
#+END_EXAMPLE

** LDIF Creation for Adding Objects on CentOS5 LPIC2 (this is Legacy)
OpenLDAP V2.3.x

- create an ldif file
/etc/openldap/mydc.ldif
#+BEGIN_EXAMPLE
dn: dc=mydomain,dc=com
dc: mydomain
description: creating my dc
objectClass: dcObject
objectClass: organizaton
o: mydomain,brq.
#+END_EXAMPLE

- add our ldif file
#+BEGIN_SRC sh
ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f mydc.ldif
#+END_SRC

- create an ldif file that will contain all our employees
/etc/openldap/myou.ldif
#+BEGIN_EXAMPLE
dn: ou=employees,dc=mydomain,dc=com
ou: employees
description: Everyon in the company
objectclass: organizationalunit
#+END_EXAMPLE

- add our employee ldif file
#+BEGIN_SRC sh
ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f myou.ldif
#+END_SRC

- adding a record
myperson.ldif
#+BEGIN_EXAMPLE
dn: cn=Robert Smith,ou=employee,dc=mydomain,dc=com
objectclass: inetOrgPerson
cn: Robert Smith
cn: Robert J Smith
cn: bob smith
sn: smith
uid: rjsmith
userpassword: p@ssw0rd
carlicense: ABC 123
homephone: 555-222-3232
mail: r.smith@mydomain.com
mail: rsmith@mydomain.com
mail: bob.smith@mydomain.com
description: Accountant
ou: Accounts
#+END_EXAMPLE

- add the new record
#+BEGIN_SRC sh
ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f myperson.ldif
#+END_SRC

- confirm that the record was added
#+BEGIN_SRC sh
slapcat
#+END_SRC
this will print out the current ldap structure with the newest record at the bottom

** Client tools for Searching, Adding and Deleting Records on CentOS5 LPIC2 (this is Legacy)
OpenLDAP V2.3.x

- search for a specific record
#+BEGIN_SRC sh
ldapsearch -x -b 'ou=employee,dc=mydomain,dc=com' '(objectclass=inetOrgPerson)' uid
#+END_SRC
this will retrieve all the uid's of the records in the "employee" organizational unit

- search for a record with cn
#+BEGIN_SRC sh
ldapsearch -x -b 'ou=employee,dc=mydomain,dc=com' '(cn=Bruce Wayne)' uid
ldapsearch -L -x -b 'ou=employee,dc=mydomain,dc=com' '(cn=Bruce Wayne)' uid
ldapsearch -LL-x -b 'ou=employee,dc=mydomain,dc=com' '(cn=Bruce Wayne)' uid
ldapsearch -LLL-x -b 'ou=employee,dc=mydomain,dc=com' '(cn=Bruce Wayne)' uid
#+END_SRC
the -L increment will limit the amount of output that is returned

- change the users password
#+BEGIN_SRC sh
ldappasswd -x -D "cn=admin,dc=mydomain,dc=com" -s IHateSuperman -W 'cn=bwayne,ou=employee,dc=mydomain,dc=com'
ldappasswd -x -D "cn=admin,dc=mydomain,dc=com" -S -W 'cn=bwayne,ou=employee,dc=mydomain,dc=com'
#+END_SRC
the second cmd will prompt for the new password

- deletign a record
#+BEGIN_SRC sh
ldapdelete "cn=Bruce Wayne,ou=employee,dc=mydomain,dc=com" -x -D "cn=admin,dc=mydomain,dc=com" -W
#+END_SRC
if successful there will be no returned output

* Lecture
** [[https://www.youtube.com/watch?v%3DjZs4p_e6H1c][What about the LDAP directory life after Sun?]]
- good explanation of migration of directories, methodology
* Tutorial
* Books
[[file://home/crito/Documents/Linux/Linux_Networking_Cookbook.pdf][Linux Networking Cookbook]]
[[file://home/crito/Documents/SysAdmin/OReilly_ldap.pdf][LDAP - O'Reilly]]
[[file://home/crito/Documents/SysAdmin/Red_Hat_Directory_Server-8.1-Deployment_Guide-en-US.pdf][Red Hat Directory Server 8.1 Deployment Guide]]
[[file://home/crito/Documents/SysAdmin/Sun-LDAP_Setup_and_Configuration_Guide.pdf][Sun - LDAP Setup and Configuration Guide]]
[[file://home/crito/Documents/SysAdmin/Addison_Wesley-LDAP_Directories_Explained.pdf][LDAP Directories Explained - Addison Wesley]]
[[file://home/crito/Documents/SysAdmin/Understanding_LDAP.pdf][Understanding LDAP - IBM]]
[[file://home/crito/Documents/SysAdmin/Red_Hat_Directory_Server-8.1-Deployment_Guide-en-US.pdf][Red Hat Directory Server 8.1]]
file://home/crito/Documents/SysAdmin/OpenLDAP_Admin_Guide_2-4.pdf
* Links
https://wiki.debian.org/LDAP
[[http://www.thegeekstuff.com/2017/07/ldap-389-directory-server-install/][How to Install LDAP 389 Directory Server On Linux]]
[[https://www.howtoforge.com/linux_openldap_setup_server_client][Step-by-Step OpenLDAP Installation and Configuration]]
[[https://www.linuxtechi.com/integrate-rhel7-centos7-windows-active-directory/][How to Integrate RHEL7 or CentOS7 with Windows Active Directory - Linux Techi]]
[[https://www.linux.com/learn/making-ldap-easy-linux-phpldapadmin][Making LDAP Easy on Linux with phpLDAPadmin - Linux.com]]
[[https://www.linux.com/learn/managing-ldap-command-line-linux][Managing LDAP from the Command Line on Linux - Linux.com]]
