#+TAGS: networking routing


* Routing
* Cmds
- netstat
- ss
- ip
- ifconfig
- route
- quagga - routing deamon suite

* Concept
** View routing information
#+BEGIN_SRC sh
netstat -rn
ip route show
#+END_SRC


** Adding and Deletign a static route
- older method
#+BEGIN_SRC sh
route add -net 172.17.0.0 netmask 255.255.255.0 gw 192.168.1.131 dev enp0s3
#+END_SRC

- newer method
#+BEGIN_SRC sh
ip route add 172.17.42.0/24 via 192.168.1.131 dev enp0s3
ip route delete 172.17.42.0/24
#+END_SRC

** Routing Policy Database
- This allows for multiple routing tables, to cater for different users.

- For this the kernel needs to be complied with "IP: advanced router" and "IP: policy routing".

- By default there are three routing tables. Route and ip cmd modify the main and local tables (by default).

The routeing rules are listed in order precedence.

<picture of ip rule list>

We see that all rules apply to all packets.

To enable more sophisticated route we create rules which point to different tables which allow us to override system wide routing rules.

** Tunnels

There are types of tunnels in linux:

1)IP in IP tunneling
2) GRE tunneling
3) Tunnels outside of the kernel e.g. PPTP

** IP in IP
This uses the two modules ipip, tunnel4 and ip\_tunnel.

> modprobe ipip
this installs all three

** GRE
  - Developed by cisco and is more advanced than IPinIP.
  - This will require the ip\_gre module.
** IPSEC
** Dynamic routing

* Lecture
* Tutorial
* Books
* Links
