#+TAGS: centos sec_d fw


* Centos7 Firewall
* Configure Firewall with FirewallD
** Zones
- These are the basic units used to group rules. 
- An interface is assigned a zone, and this dictates the behaviour that the fw should allow.
- These zones allow flexibility for machines that move between networks (i.e. laptops).

*** Pre-defined Zones (least trusted to most trusted)
drop - All incoming connections are dropped without reply and only outgoing connections are possible.
block - Similar to the above, but instead of simply dropping connections, incoming requests are rejected with an icmp-host-prohibited or icmp6-adm-prohibited message.
public - Represents public, untrusted networks. You don't trust other computers but may allow selected incoming connections on a case-by-case basis.
external - External networks in the event that you are using the firewall as your gateway. It is configured for NAT masquerading so that your internal network remains private but reachable.
internal - The other side of the external zone, used for the internal portion of a gateway. The computers are fairly trustworthy and some additional services are available.
dmz - Used for computers located in a DMZ (isolated computers that will not have access to the rest of your network). Only certain incoming connections are allowed.
work - Used for work machines. Trust most of the computers in the network. A few more services might be allowed.
home - A home environment. It generally implies that you trust most of the other computers and that a few more services will be accepted.
trusted - Trust all of the machines in the network. The most open of the available options and should be used sparingly.

** Rule Permanence
- Altered rules will take effect immediately, but on reboot will revert to originally set rules.
- The --permanent flag will push the rule to the non-ephemeral firewall. This rule will then be activeated on the next reboot.

** Defaults
- the zone is set as public by default.

** Setting Interface to a Zone Permanently  
alter the ZONE variable in /etc/sysconfig/network-scripts/ifcfg-eth0
ZONE=home
*** To implement the new zone
Restart the network and firewall service
#+BEGIN_SRC sh
systemctl restart network.service
systemctl restart firewalld.service
#+END_SRC
Check the firewall properties
#+BEGIN_SRC sh
firewall-cmd --get-active-zones
#+END_SRC

** Setting Rules for Applications
- Services are named and more details can be found about them by looking at the .xml files corresponding to the service found at /var/lib/firewalld/services
- Add a service with the --add-service parameter
#+BEGIN_SRC sh
firewall-cmd --zone=home --add-service=http
#+END_SRC
- the --permanent parameter needs to be set for it to come into effect on reboot.
  
** Opening a Port for your Zones
- the --add-port parameter is used to set a port to a zone
#+BEGIN_SRC sh
firewall-cmd --zone=public --add-port=80/tcp
#+END_SRC
*** Opening a Port range
#+BEGIN_SRC sh
firewall-cmd --zone=public --add-port=4400-4450/udp
#+END_SRC
    
** Defining a Service
- managing a service is easier than remembering ports and the associated ports
- copying one of the service xml files in /usr/lib/firewalld/services and using it as a template to define your own service
#+BEGIN_SRC sh
cp /usr/lib/firewalld/services/service.xml /etc/firewalld/services/example.xml
#+END_SRC
- to get access to your new service reload the firewall
#+BEGIN_SRC sh
systemctl restart firewalld.service
#+END_SRC

** Usage
*** Start service
#+BEGIN_SRC sh
systemctl start firewalld.service
#+END_SRC

*** What is the current status
#+BEGIN_SRC sh
firewall-cmd --list-all
#+END_SRC

*** What is the current zone
#+BEGIN_SRC sh
firewall-cmd 
#+END_SRC
    
*** Change interface zone
#+BEGIN_SRC sh
firewall-cmd --zone=home --change-interface=eth0
#+END_SRC
  
*** List of All Available Services
#+BEGIN_SRC sh
firewall-cmd --get-services
#+END_SRC

* Cmds
** firewalld
** [[file://home/crito/org/tech/cmds/firewall-cmd.org][firewall-cmd]]
* Links
[[https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-using-firewalld-on-centos-7][Configure Firewall with FirewallD - Digital Ocean]]
* Configure Firewall with Iptables
* Cmds
* Lecture
* Tutorial
* Books
* Links
