#+TAGS: kernel


* Kernel Build                                                       :kernel:
* Description
* Usage
** Building the Kernel
1. git or wget source code
#+BEGIN_SRC sh
git clone https://github.com/torvalds/linux.git
#+END_SRC

2. Make the .config file for the kerrnel build
We have 3 options
i) copy current distro .config form /proc/config.gz
#+BEGIN_SRC sh
zcat /proc/config.gz > .config
#+END_SRC
or
#+BEGIN_SRC sh
cp /usr/lib/modules/$(uname -r)/build/.config ./
cp /usr/lib/modules/$(uname -r)/build/Module.symvers ./
#+END_SRC

This should create a kernel that runs on your current distro

ii) each build normally comes with a generic .config 
#+BEGIN_SRC sh
make defconfig
#+END_SRC

iii) a custom .config can be created using
#+BEGIN_SRC sh
make config
#+END_SRC
This will setp through every configuration option

This can also be done with one of the three graphical Uis
  - menuconfig - ncurses based graphical ui
  - gconfig - GTK+ based graphical ui
  - xconfig - QT-based graphical ui
This option is time consuming and will ask you which of the thousands of parameters to set.

3. Now we have the .config we can build the kernel
#+BEGIN_SRC sh
make
#+END_SRC
This will create a kernel to the .config specification

The build process can be speeded up on a multi-core machine with the -j flag
#+BEGIN_SRC sh
make -j4
#+END_SRC
This will tell the build that we have four processors/cores

4. 
** Install the Kernel Manually
1. Make the modules for the new Kernel
#+BEGIN_SRC sh
make modules_install
#+END_SRC

2. Move the newly created kernel to the boot directory
#+BEGIN_SRC sh
cp arch/x86/boot/bzImage /boot/bzImage-Kernel_Version
cp System.map /boot/System.map-Kernel_Version
#+END_SRC

3. The boot loader will also need to be updated.
#+BEGIN_SRC sh
update-grub
#+END_SRC

4. If on reboot the kernel fails to boot it may be due to the ramdisk. To solve this use the distro kernel installation method to create the initrd.img 

** Upgrading a Kernel
1. backup the .config
#+BEGIN_SRC sh
cp .config ~/good_config
#+END_SRC

2. Pull the latest source code
#+BEGIN_SRC sh
git clone https://github.com/torvalds/linux.git
#+END_SRC

3. Apply the changes to the old source tree to bring it up to the newer level.
   
4. Build the new Kernel.(Follow Instructions above)

5. Install the new Kernel.(Follow Instructions above)

* Lecture
* Tutorial
* Books
* Links
[[https://wiki.archlinux.org/index.php/Kernels/Arch_Build_System][Arch Build System]]
[[http://www.berkes.ca/guides/linux_kernel.html][Jem's Guide: How to compile and install a new Linux Kernel]]
[[http://docs.slackware.com/howtos:slackware_admin:building_the_linux_kernel_using_git_repository][Slackware - Building the Linux Kernel using Git repository]]
