#+TAGS: virt dev


* Vagrant							   :virt:dev:
* Usage
** Cmds
- list boxes
> vagrant list
- remove box
> vagrant box remove <NAME>
- status of box
> vagrant status

+ Virtualbox Guest Additions
To ensure there is no vb guest addmitions mismatch the vagrant plugin can be used.
This is installed with:
> vagrant plugin install vagrant-vbguest

+ Guest OS States
- running
- poweroff
- saved
- not created
- aborted
  
** Vagrantfile
This file is used to maintain that development is performed on the same platfrom by all involved in the project.

+ Variables
  - config.vm.box = <url_to_box>
  - config.vm.network :forward_port, guest: 4567, host: 45670, host_ip: "127.0.0.1" - this will restrict remote access using localhost
  - VAGRANTFILE_API_VERSION = "2" - this will used version 2 format
   
** Boxes
  - This is the base image that vagrant uses for the OS.
  - The suffix used is usually .box but that is not mandatory.
  - Once the box has been downloaded it is stored in $HOME/.vagrant.d/boxes. These boxes are then used as templates for projects.

* Description
* Usage
* Lecture
* Tutorial
* Books
[[file://home/crito/Documents/SysAdmin/Virtulization/Vagrant/Pro%20Vagrant.pdf][Pro Vagrant]]
[[file://home/crito/Documents/SysAdmin/Virtulization/Vagrant/vagrant.pdf][Vagrant - O'reilly]]

* Links


